#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: proxmox
  tasks:

    - name: fact vm sequence names
      vars:
        _sequence_arg: "{{ s | default('',true) }}"
        _sequence_arg_names: "{{ _sequence_arg
          if(_sequence_arg | type_debug == 'list')
          else(_sequence_arg | string | split(',')) }}"
      ansible.builtin.set_fact:
        vm_sequence_names: >-
          {{
          (vm.sequence | default([],true))
          + (_sequence_arg_names | map('trim') | reject('equalto','') | list)
          }}

    - name: prompt vm sequence names
      when: vm_sequence_names | length == 0
      include_tasks: "{{ playbook_dir }}/../../.seed/ansible-tasks/seed-sequence.loop-prompt.yml"
      vars:
        sequence:
          path: vm.sequences
          fact: vm_sequence_names

    - name: validate vm sequence names
      when: vm_sequence_names | length > 0
      vars:
        _sequence_invalid_names: "{{ vm_sequence_names
          | difference((vm.sequences | default({},true)).keys() | list) }}"
      ansible.builtin.assert:
        that:
          - _sequence_invalid_names | length == 0
        fail_msg: |
          unknown vm.sequences key(s): {{ _sequence_invalid_names | join(', ') }}
          available vm.sequences key(s): {{
            (vm.sequences | default({},true)).keys() | list | join(', ')
          }}

    - name: run vm sequence names
      vars:
        vm_deployer: "{{ vm.sequences[vm_sequence_name] }}"
      ansible.builtin.include_tasks: ansible-tasks.deploy.yml
      loop: "{{ vm_sequence_names }}"
      loop_control:
        loop_var: vm_sequence_name
