#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: proxmox
  tasks:

    - name: deploy vm
      vars:
        pubkey: "{{ vm.pubkey | default(None,true) }}"
        template: "{{ vm.template | default(None,true) }}"
        kvm: "{{ vm.kvm | default(None,true) }}"
        config: "{{ vm.config | default(None,true) }}"
        command: "{{ vm.command | default(None,true) }}"
      include_tasks: ansible-tasks.deploy.yml

    - name: deploy group vm
      vars:
        group_names: "{{ vm.groups | default([],true) }}"
        group_var: "{{ vm_groups[group_name] | default({},true) }}"
        pubkey: "{{ group_var.pubkey | default(None,true) }}"
        template: "{{ group_var.template | default(None,true) }}"
        kvm: "{{ group_var.kvm | default(None,true) }}"
        config: "{{ group_var.config | default(None,true) }}"
        command: "{{ group_var.command | default(None,true) }}"
      loop: "{{ group_names }}"
      loop_control:
        loop_var: group_name
      include_tasks: ansible-tasks.deploy.yml
