# code: language=ansible
---

- rescue:
  - name: vm.deploy|pubkey|rescue|fail tasks
    when:
      - pubkey | default(None,true) != None
    ansible.builtin.fail:
      msg: "deploy vm fail. exclude var undefined."

  block:
  - name: vm.deploy|pubkey|assert var
    ansible.builtin.assert:
      that:
        - pubkey | default(None,true) != None
      msg: "var eval fail {{ pubkey }}"
      quiet: true

  - name: vm.deploy|pubkey|fact param
    ansible.builtin.set_fact:
      _vm:
        pubkey: "{{ pubkey }}"

  - name: vm.deploy|pubkey|add pubkey
    vars:
      pubkey: "{{ _vm.pubkey }}"
    include_tasks: ../seed/pve-pubkey.add.yml

- rescue:
  - name: vm.deploy|template|rescue|fail tasks
    when:
      - template | default(None,true) != None
    ansible.builtin.fail:
      msg: "deploy vm fail. exclude var undefined."

  block:
  - name: vm.deploy|template|assert var
    ansible.builtin.assert:
      that:
        - template | default(None,true) != None
      msg: "var eval fail {{ template }}"
      quiet: true

  - name: vm.deploy|template|fact param
    ansible.builtin.set_fact:
      _vm:
        template: "{{ template }}"

  - name: vm.deploy|template|pveam update
    ansible.builtin.shell:
      cmd: pveam update

  - name: vm.deploy|template|add templates
    vars:
      templates: "{{ _vm.template }}"
    when: templates | length > 0
    include_tasks: ../seed/pve-templates.add.yml

- rescue:
  - name: vm.deploy|kvm|rescue|fail tasks
    when:
      - kvm | default(None,true) != None
    ansible.builtin.fail:
      msg: "deploy kvm fail. exclude var undefined."

  block:
  - name: vm.deploy|kvm|assert var
    ansible.builtin.assert:
      that:
        - kvm | default(None,true) != None
      msg: "var eval fail {{ kvm }}"
      quiet: true

  - name: vm.deploy|kvm|fact param
    ansible.builtin.set_fact:
      _vm:
        kvm: "{{ kvm }}"

  - name: vm.deploy|kvm|add kvm
    vars:
      kvm: "{{ _vm.kvm }}"
    include_tasks: ../seed/pve-kvm.add.yml

- rescue:
  - name: vm.deploy|config|rescue|fail tasks
    when:
      - config | default(None,true) != None
    ansible.builtin.fail:
      msg: "deploy config fail. exclude var undefined."

  block:
  - name: vm.deploy|config|assert var
    ansible.builtin.assert:
      that:
        - config | default(None,true) != None
      msg: "var eval fail {{ config }}"
      quiet: true

  - name: vm.deploy|config|fact param
    ansible.builtin.set_fact:
      _vm:
        config: "{{ config }}"

  - name: vm.deploy|config|add config
    vars:
      config_type:
        type: qemu-server
      config: "{{ _vm.config | combine(config_type, recursive=True) }}"
    include_tasks: ../seed/pve-config.add.yml
