# code: language=ansible
---

- name: vm.deploy|assert param
  ansible.builtin.assert:
    that:
      - vm_deployer is defined
    msg: "param undefined 'vm_deployer'"
    quiet: true

- name: vm.deploy|debug param
  ansible.builtin.debug:
    msg: "{{ vm_deployer }}"
    verbosity: 3

# This fact is only as a prototype for update_fact.
# The value will not be updated.
- name: vm.deploy|ensure _param exist
  ansible.builtin.set_fact:
    _param:
      pubkey: {}
      template: {}
      kvm: {}
      config: {}
      command: {}

- name: vm.deploy|append _param attrs
  ansible.utils.update_fact:
    updates:
      - path: "_param"
        value: "{{ vm_deployer | default({},true) }}"
  register: vm_deploy

- name: vm.deploy|add pubkey
  when: vm_deploy._param.pubkey | default(None,true) != None
  include_tasks: ../seed/pve-pubkey.add.yml
  vars:
    pubkey_adder: "{{ vm_deploy._param.pubkey }}"

- name: vm.deploy|add template
  when: vm_deploy._param.template | default(None,true) != None
  include_tasks: ../seed/pve-template.add.yml
  vars:
    template_adder: "{{ vm_deploy._param.template }}"

- name: vm.deploy|add kvm
  when: vm_deploy._param.kvm | default(None,true) != None
  include_tasks: ../seed/pve-kvm.add.yml
  vars:
    kvm_adder: "{{ vm_deploy._param.kvm }}"

- name: vm.deploy|add config
  when: vm_deploy._param.config | default(None,true) != None
  include_tasks: ../seed/pve-config.add.yml
  vars:
    config_adder: "{{ vm_deploy._param.config | combine({'type': 'qemu-server'}, recursive=True) }}"

- name: vm.deploy|run command
  when: vm_deploy._param.command | default(None,true) != None
  include_tasks: "{{ playbook_dir }}/../../.seed/ansible-tasks/seed-command.run.yml"
  vars:
    command_run: "{{ vm_deploy._param.command }}"
