version: "3.8"

networks:
  frp:
    name: frp_frp
    attachable: true

services:
  frp-server:
    image: fatedier/frps:v0.44.0
    env_file: external_env-all.env
    entrypoint:
      - "/usr/bin/frps"
      - "-c"
      - "/app/frps.ini"
    volumes:
      - ./bind_file-frps.ini:/app/frps.ini
    networks:
      - frp
    ports:
      - "80"
      - "443"
      - "7001:7001"
      - "7002:7002"
      - "7400:7400"
      - "7500:7500"
    # network_mode: "host"
    container_name: frp-server
    restart: always
