version: "3.8"

volumes:
  data:
    name: external_vol-uptime-kuma
    external: true

networks:
  uptime-kuma:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    env_file: external_env-all.env
    volumes:
      - data:/app/data
    networks:
      - uptime-kuma
    ports:
      - 3001:3001
    # network_mode: bridge
    container_name: uptime-kuma
    restart: always
    # healthcheck:
    #   test: nc -z localhost 80 || exit 1
    #   interval: 60s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 10m
