version: "3.8"

volumes:
  certs:
    name: external_vol-derper-certs
    external: true

services:
  derper:
    image: fredliang/derper:latest
    env_file: external_env-all.env
    environment:
      - DERP_CERT_DIR=/app/certs
      # - DERP_ADDR=:443
      # - DERP_HTTP_PORT=80
    volumes:
      - certs:/app/certs
      # if you use DERP_VERIFY_CLIENTS,
      # you nee to mount tailscaled.sock so that that container can access the external machine's derper proces
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    # Use the host network to support running on any ports
    # 1. run on 443 port for auto certificate
    # 2. run reverse proxy on 443 with any port for auto certificate
    # 3. run on any port for manual certificate
    # ports:
    #   - 8480:80
    #   - 14443:443
    #   # stun port
    #   - 3478:3478/udp
    network_mode: "host"
    container_name: derper
    restart: always
