# code: language=ansible
---

- name: script.build|assert param
  ansible.builtin.assert:
    that:
      - image_builder is defined
      - image_builder.release is defined
      - image_builder.target is defined
    msg: "param undefined 'image_builder.release' or 'image_builder.target'"
    quiet: true

- name: script.build|debug param
  ansible.builtin.debug:
    msg: "{{ image_builder }}"
    verbosity: 3

# This fact is only as a prototype for update_fact.
# The value will not be updated.
- name: script.build|ensure _params/_path exist
  vars:
    dl_snapshots_name: "openwrt-imagebuilder-{{ image_builder.target }}.Linux-x86_64"
    dl_release_name: "openwrt-imagebuilder-{{ image_builder.release }}-{{ image_builder.target }}.Linux-x86_64"
    dl_name: "{{ (image_builder.release == 'snapshots') | ternary(dl_snapshots_name,dl_release_name) }}"
    dl_file: "{{ image_builder.url | basename if image_builder.url is defined else dl_name + '.tar.zst' }}"
    dl_target_path: "targets/{{ image_builder.target | regex_replace('-', '/') }}"
    dl_snapshots_path: "snapshots/{{ dl_target_path }}"
    dl_release_path: "releases/{{ image_builder.release }}/{{ dl_target_path }}"
    dl_path: "{{ (image_builder.release == 'snapshots') | ternary(dl_snapshots_path,dl_release_path) }}"
  ansible.builtin.set_fact:
    _params:
      release: <release>
      target: <target>
      id: "{{ lookup('community.general.random_string', upper=false, special=false) }}"
      url: "https://downloads.openwrt.org/{{ dl_path }}/{{ dl_file }}"
      # not support `$HOME`
      file: "~/.openwrt/{{ dl_file }}"
      # not support `$HOME`
      path: "~/.openwrt/{{ dl_name }}@{{ inventory_hostname }}/{{ dl_name }}"
      command: "make image"
      config: {}
      repositories: ""
      option: {}
      output:
        path: build_dir/target-x86_64_musl/linux-x86_64/tmp/
        dest: "{{ inventory_dir }}/../image/{{ inventory_hostname }}/{{ image_builder.release }}/"
        mode: copy
    _path:
      env: "{{ inventory_dir }}/../image/{{ inventory_hostname }}/{{ image_builder.release }}/"
      script: "{{ inventory_dir }}/../image/{{ inventory_hostname }}/{{ image_builder.release }}/"

- name: script.build|append _params/_path attrs
  ansible.utils.update_fact:
    updates:
      - path: "_params.release"
        value: "{{ image_builder.release | default(_params.release,true) }}"
      - path: "_params.target"
        value: "{{ image_builder.target | default(_params.target,true) }}"
      - path: "_params.url"
        value: "{{ image_builder.url | default(_params.url,true) }}"
      - path: "_params.file"
        value: "{{ image_builder.file | default(_params.file,true) }}"
      - path: "_params.path"
        value: "{{ image_builder.path | default(_params.path,true) }}"
      - path: "_params.command"
        value: "{{ image_builder.command | default(_params.command,true) }}"
      - path: "_params.config"
        value: "{{ image_builder.config | default(_params.config,true) }}"
      - path: "_params.repositories"
        value: "{{ image_builder.repositories | default(_params.repositories,true) }}"
      - path: "_params.option"
        value: "{{ image_builder.option | default(_params.option,true) }}"
      - path: "_params.output.path"
        value: "{{ image_builder.output.path | default(_params.output.path,true) }}"
      - path: "_params.output.dest"
        value: "{{ image_builder.output.dest | default(_params.output.dest,true) }}"
      - path: "_path.env"
        value: "{{ script_builder.path | default(_path.env,true) }}/image-bulld.env"
      - path: "_path.script"
        value: "{{ script_builder.path | default(_path.script,true) }}/image-build.bash"
  register: script_build

- name: script.build|mkdir output
  ansible.builtin.file:
    state: directory
    path: "{{ script_build._path.env | dirname }}"

- name: script.build|template env file
  vars:
    IMAGE_BUILDER: "{{ script_build._params }}"
  ansible.builtin.template:
    dest: "{{ script_build._path.env }}"
    src: "image-build.env.j2"

- name: script.build|copy bash file
  ansible.builtin.copy:
    dest: "{{ script_build._path.script }}"
    src: "image-build.bash"
