#!/bin/bash

set -e

_usage() {
	echo "env undefined 'BUILDER_RELEASE' or 'BUILDER_TARGET'"
	echo "Usage: $0 [/path/to/image-build.env]"
	exit 1
}

source_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

[[ -z "$config_file" ]] && config_file=$1
[[ -z "$config_file" ]] && config_file="$source_directory/image-build.env"
if [[ -f "$config_file" ]];
then
	source "$config_file"
fi

[[ -z "$BUILDER_RELEASE" || -z "$BUILDER_TARGET" ]] && _usage

if [[ "$BUILDER_RELEASE" == "snapshots" ]];
then
    dl_name="openwrt-imagebuilder-$BUILDER_TARGET.Linux-x86_64"
    dl_path="snapshots/targets/${BUILDER_TARGET/-//}"
else
    dl_name="openwrt-imagebuilder-$BUILDER_RELEASE-$BUILDER_TARGET.Linux-x86_64"
    dl_path="releases/$BUILDER_RELEASE/targets/${BUILDER_TARGET/-//}"
fi
dl_file="$dl_name.tar.zst"
[[ -z "$BUILDER_URL" ]] && BUILDER_URL="https://downloads.openwrt.org/$dl_path/$dl_file"
dl_file="$( basename "$BUILDER_URL" )"
[[ -z "$BUILDER_FILE" ]] && BUILDER_FILE="$HOME/.openwrt/$dl_file"
[[ -z "$BUILDER_NAME" ]] && BUILDER_NAME="$dl_name"
[[ -z "$BUILDER_PATH" ]] && BUILDER_PATH="$source_directory/$BUILDER_NAME"
[[ -z "$BUILDER_ID" ]] && BUILDER_ID="$( echo $RANDOM | md5sum | head -c 20 )"
[[ -z "$BUILDER_COMMAND" ]] && BUILDER_COMMAND="make image"
[[ -z "$BUILDER_OUTPUT_MODE" ]] && BUILDER_OUTPUT_MODE=copy

BUILDER_DIR="$BUILDER_PATH"
if [[ ! -d "$BUILDER_DIR" ]];
then
    if [[ ! -f "$BUILDER_FILE" ]];
    then
        mkdir -p "$HOME/.openwrt"

        echo "download $BUILDER_URL"
        curl -o "$BUILDER_FILE" "$BUILDER_URL"
    fi
    mkdir -p "$( dirname "$BUILDER_DIR" )"
    case "$BUILDER_FILE" in
        *.tar.zst)
            tar -I zstd -xf "$BUILDER_FILE" -C "$( dirname "$BUILDER_DIR" )"
            ;;
        *.tar.xz)
            tar -Jxf "$BUILDER_FILE" -C "$( dirname "$BUILDER_DIR" )"
            ;;
        *.tar.gz|*.tgz)
            tar -zxf "$BUILDER_FILE" -C "$( dirname "$BUILDER_DIR" )"
            ;;
        *.tar)
            tar -xf "$BUILDER_FILE" -C "$( dirname "$BUILDER_DIR" )"
            ;;
        *)
            echo "Unsupported builder archive: $BUILDER_FILE"
            exit 1
            ;;
    esac
fi

cd "$BUILDER_DIR"

# make info
make info

if [[ -f "$BUILDER_DIR/.config" && ! -f "$BUILDER_DIR/.config.original" ]];
then
    # backup config
    cp "$BUILDER_DIR/.config" "$BUILDER_DIR/.config.original"
fi
read -r -a envs_config <<< "$( echo "${!BUILDER_CONFIG_*}" )"
if [[ -f "$BUILDER_DIR/.config" && -n "${envs_config[@]}" ]];
then
    if [[ -f "$BUILDER_DIR/.config.original" ]];
    then
        # restore config
        cp "$BUILDER_DIR/.config.original" "$BUILDER_DIR/.config"
    fi

    echo ""
    echo "# auto generated by seed" >> "$BUILDER_DIR/.config"

    for env_name in "${envs_config[@]}";
    do
        config_key="${env_name/BUILDER_CONFIG_/}"
        config_value="${!env_name}"
        echo "Config Replace: $config_key=$config_value"
        sed -i "s|^ *$config_key|# &|" "$BUILDER_DIR/.config"
        echo "$config_key=$config_value" >> "$BUILDER_DIR/.config"
    done
fi

for repositories_conf in "$BUILDER_DIR/repositories" "$BUILDER_DIR/repositories.conf";
do
    if [[ -f "$repositories_conf" ]];
    then
        BUILDER_REPOSITORIES_CONF="$repositories_conf"
        break
    fi
done
if [[ -n "$BUILDER_REPOSITORIES_CONF" ]];
then
    if [[ ! -f "$BUILDER_REPOSITORIES_CONF.original" ]];
    then
        # backup repositories
        cp "$BUILDER_REPOSITORIES_CONF" "$BUILDER_REPOSITORIES_CONF.original"
    fi

    if [[ -v BUILDER_REPOSITORIES ]];
    then
        if [[ -f "$BUILDER_REPOSITORIES_CONF.original" ]];
        then
            # restore repositories
            cp "$BUILDER_REPOSITORIES_CONF.original" "$BUILDER_REPOSITORIES_CONF"
        fi

        echo "Repositories Replace: https://downloads.openwrt.org=$BUILDER_REPOSITORIES"
        sed -i "s|https://downloads.openwrt.org|$BUILDER_REPOSITORIES|g" "$BUILDER_REPOSITORIES_CONF"
    fi
fi

BUILDER_COMMAND_RUN="$BUILDER_COMMAND"
read -r -a envs_option <<< "$( echo "${!BUILDER_OPTION_*}" )"
for env_name in "${envs_option[@]}";
do
    option_key="${env_name/BUILDER_OPTION_/}"
    option_value="${!env_name}"
    option_value="${option_value//$'\n'/}"
    printf -v option_value_quoted "%q" "$option_value"

    BUILDER_COMMAND_RUN="$BUILDER_COMMAND_RUN $option_key=$option_value_quoted"
done

echo ""
# make image
bash -c "$BUILDER_COMMAND_RUN"

# copy output
if [[ -n "$BUILDER_OUTPUT_DEST" ]];
then
    mkdir -p "$BUILDER_OUTPUT_DEST"

    if [[ -n "$BUILDER_OUTPUT_PATH" ]];
    then
        BUILDER_OUTPUT_SRC="$BUILDER_DIR/$BUILDER_OUTPUT_PATH"
        if [[ "$BUILDER_OUTPUT_PATH" =~ \/$ ]];
        then
            cp -r "$BUILDER_OUTPUT_SRC." "$BUILDER_OUTPUT_DEST"
        else
            cp -r "$BUILDER_OUTPUT_SRC" "$BUILDER_OUTPUT_DEST"
        fi

        if [[ "$BUILDER_OUTPUT_MODE" == "move" ]];
        then
            rm -rf "$BUILDER_OUTPUT_SRC"
        fi
    fi
fi
