# code: language=ansible
---

- name: enabler.download|get latest
  ansible.builtin.uri:
    url: "https://api.github.com/repos/adyanth/openwrt-tailscale-enabler/releases/latest"
    return_content: true
  register: latest_get

- name: enabler.download|fact _enabler
  vars:
    version: "{{ latest_get.json.name }}"
  ansible.builtin.set_fact:
    _enabler:
      # url -> file -> path
      version: "{{ version }}"
      url: "{{ latest_get.json.assets[0].browser_download_url }}"
      file: "~/.openwrt/openwrt-tailscale-enabler-{{ version }}.tgz"
      path: "~/.openwrt/openwrt-tailscale-enabler-{{ version }}"

- name: enabler.download|mkdir enabler file
  ansible.builtin.file:
    state: directory
    path: "{{ _enabler.file | dirname }}"

- name: enabler.download|download enabler file
  ansible.builtin.get_url:
    dest: "{{ _enabler.file }}"
    url: "{{ _enabler.url }}"

- name: enabler.download|mkdir enabler path
  ansible.builtin.file:
    state: directory
    path: "{{ _enabler.path }}"

- name: enabler.download|unzip enabler file
  ansible.builtin.unarchive:
    dest: "{{ _enabler.path }}"
    src: "{{ _enabler.file }}"

- when: tailscale.enabler.pkg | default(false)
  block:
  - name: enabler.download|get arch
    delegate_to: !!null
    ansible.builtin.shell: uname -m
    register: arch_get

  - name: enabler.download|get endianness
    delegate_to: !!null
    when: arch_get.stdout == 'mips'
    ansible.builtin.shell: |
      echo -n I | hexdump -o | awk '{ print (substr($2,6,1)=="1") ? "le" : ""; exit }'
    register: endianness_get

  - name: enabler.download|fact pkg
    vars:
      archs:
        mips: "mips"
        armv7l: "arm"
        aarch64: "arm64"
        x86_64: "amd64"
      regex_hash_suffix: '-\w{7}-.*'
      regex_version_prefix: '^v'
      tailscale_version: "{{ _enabler.version | regex_replace(regex_hash_suffix,'') | regex_replace(regex_version_prefix,'') }}"
      arch: "{{ archs[arch_get.stdout] }}{{ endianness_result.stdout | default('',true) }}"
      version: "{{ tailscale_version }}_{{ arch }}"
    ansible.builtin.set_fact:
      _pkg:
        version: "{{ version }}"
        url: "https://pkgs.tailscale.com/stable/tailscale_{{ version }}.tgz"
        file: "~/.openwrt/tailscale_{{ version }}.tgz"
        path: "~/.openwrt/tailscale_{{ version }}"

  - name: enabler.download|download pkg file
    ansible.builtin.get_url:
      dest: "{{ _pkg.file }}"
      url: "{{ _pkg.url }}"

  - name: enabler.download|mkdir pkg path
    ansible.builtin.file:
      state: directory
      path: "{{ _pkg.path }}"

  - name: enabler.download|unzip pkg file
    ansible.builtin.unarchive:
      dest: "{{ _pkg.path }}"
      src: "{{ _pkg.file }}"

  - name: enabler.download|mkdir pkg enabler
    ansible.builtin.file:
      state: directory
      path: "{{ _enabler.path }}/tmp"

  - name: enabler.download|copy pkg enabler
    loop:
      - "tailscale"
      - "tailscaled"
    ansible.builtin.copy:
      src: "{{ _pkg.path }}/tailscale_{{ _pkg.version }}/{{ item }}"
      dest: "{{ _enabler.path }}/tmp/{{ item }}"
