version: "3.8"

volumes:
  data:
    name: external_vol-nexus-data
    external: true

services:
  nexus3:
    image: sonatype/nexus3:3.42.0
    env_file: external_env-all.env
    # environment:
    #   PUID: 200
    #   INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m"
    volumes:
      - data:/nexus-data
    ports:
      - 8081:8081
      - 8082:8082
    # network_mode: bridge
    container_name: nexus3
    restart: always
    healthcheck:
      test: curl -f http://localhost:8081 || exit 1
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 10m
