# code: language=ansible
---

- name: tailscale-network.up|wait container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.wait.yml"
  vars:
    container:
      name: tailscale
      until:
        - container_info.exists
      retries: 60
      delay: 60

- name: tailscale-network.up|exec container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.exec.yml"
  vars:
    container:
      container: tailscale
      command: "tailscale up --authkey={{ tailscale.authkey }} {{ tailscale.network.flags | default('',true) }}"
      register: container_exec
