#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: build
  hosts: edgeos
  connection: local
  tasks:

    - name: mkdir build
      delegate_to: localhost
      connection: local
      ansible.builtin.file:
        state: directory
        path: "{{ inventory_dir }}/../host/{{ inventory_hostname }}"

    - name: build host
      vars:
        lines: "{{ host.lines | default([],true) }}"
        dest: "{{ inventory_dir }}/../host/{{ inventory_hostname }}/host.configure.sh"
      include_tasks: ansible-tasks.build.yml

    - name: build group host
      vars:
        group_names: "{{ host.groups | default([],true) }}"
        group_var: "{{ host_groups[group_name] | default({},true) }}"
        lines: "{{ group_var.lines }}"
        dest: "{{ inventory_dir }}/../host/{{ inventory_hostname }}/host.{{ group_name }}.configure.sh"
      loop: "{{ group_names }}"
      loop_control:
        loop_var: group_name
      include_tasks: ansible-tasks.build.yml
