version: "3.8"

volumes:
  etc:
    name: shadowsocks-python-etc

services:
  shadowsocks-python:
    image: teddysun/shadowsocks-python:latest
    env_file: external_env-python.env
    volumes:
      - ./bind_file-python.json:/etc/shadowsocks-python/config.json
      - etc:/etc/shadowsocks-python
    network_mode: host
    container_name: shadowsocks-python
    restart: always