# code: language=ansible
---

- name: pve-kvm.add|assert param
  ansible.builtin.assert:
    that:
      - proxmox is defined
      - proxmox.api_host is defined
      - proxmox.api_user is defined
      - proxmox.api_password is defined
    msg: "param undefined 'proxmox.api_host' or 'proxmox.api_user' or 'proxmox.api_password'"
    quiet: true

- name: pve-kvm.add|assert param
  ansible.builtin.assert:
    that:
      - kvm_adder is defined
    msg: "param undefined 'kvm_adder'"
    quiet: true

- name: pve-kvm.add|debug param
  ansible.builtin.debug:
    msg: "{{ kvm_adder }}"
    verbosity: 3

# This fact is only as a prototype for update_fact.
# The value will not be updated.
- name: pve-kvm.add|ensure _params exist
  ansible.builtin.set_fact:
    _params: {}

- name: pve-kvm.add|append _params attrs
  ansible.utils.update_fact:
    updates:
      - path: "_params"
        value: "{{ kvm_adder }}"
  register: kvm_add

- name: pve-kvm.add|add kvm
  delegate_to: localhost
  vars:
    combine:
      api_host: "{{ proxmox.api_host }}"
      api_user: "{{ proxmox.api_user }}"
      api_password: "{{ proxmox.api_password }}"
    args: "{{ kvm_add._params | combine(combine, recursive=True) }}"
  community.proxmox.proxmox_kvm: "{{ args }}"
  register: kvm_proxmox
  until: kvm_proxmox is succeeded
  # There is a chance that when state=started, the error "An error occurred: 'name'" will occur.
  retries: 10
  delay: 5
