# code: language=ansible
---

- name: pve-templates.add|assert var
  ansible.builtin.assert:
    that:
      - templates is defined
      - templates | type_debug == 'list'
    msg: "var eval fail {{ templates }}"
    quiet: true

- name: pve-templates.add|fact param
  ansible.builtin.set_fact:
    _templates: "{{ templates | flatten }}"

- vars:
    share_mode: "{{ templates_share.mode | default('index') }}"
    share_group: "{{ templates_share.group | default('all',true) }}"
  block:
  - name: pve-templates.add|index|loop
    loop: "{{ range(0, _templates | length, 1) | list }}"
    loop_control:
      loop_var: template_index
    when:
      - share_mode == 'index'
      - inventory_hostname in groups[template_share.group] | default([],true)
    include_tasks: pve-template.add.yml
    vars:
      template: "{{ _templates[template_index] }}"
      template_share:
        any: false
        group: "{{ template.group | default(share_group,true) }}"

  - name: pve-templates.add|value|loop
    loop: "{{ _templates }}"
    loop_control:
      loop_var: template
    when:
      - share_mode == 'value'
      - inventory_hostname in groups[template_share.group] | default([],true)
    include_tasks: seed-task.once.yml
    vars:
      task_share:
        run_once: "{{ template.once | default(false) }}"
        task: pve-template.add.yml
      template_share:
        any: "{{ template.any | default(false) }}"
        group: "{{ template.group | default(share_group,true) }}"

- name: pve-templates.add|unfact param
  run_once: true
  ansible.builtin.set_fact:
    _templates: !!null
