# code: language=ansible
---

- name: pve-pubkey.fact|fact pubkey
  vars:
    parts_keypair_path:
      - "{{ _ssh.dir }}"
      - "{{ _ssh.name }}"
      - "id_rsa.pub"
    local_pub_path: "{{ parts_keypair_path | path_join }}"
  when: pubkey_add._params.name is defined
  ansible.builtin.set_fact:
    pubkey_fact:
      name: "{{ pubkey_add._params.name }}"
      key: "{{ lookup('file', local_pub_path | path_join) }}"
