version: '3'

volumes:
  data:

services:
  portainer:
    image: portainer/portainer-ce:latest
    env_file: external_env-all.env
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
      - 9443:9443
      - 8000:8000
    # network_mode: bridge
    container_name: portainer
    restart: always
