# code: language=ansible
---

- name: openwrt-pip.install|assert param
  ansible.builtin.assert:
    that:
      - pip_installer is defined
      - pip_installer['loop.ansible.builtin.pip'] is defined
    msg: "param undefined 'pip_installer['loop.ansible.builtin.pip']'"
    quiet: true

- name: openwrt-pip.install|debug param
  ansible.builtin.debug:
    msg: "{{ pip_installer }}"
    verbosity: 3

# This fact is only as a prototype for update_fact.
# The value will not be updated.
- name: openwrt-pip.install|ensure _params exist
  ansible.builtin.set_fact:
    _params:
      proxy: null
      include:
        role: xiaoyao9184.ansible-role-pip-configure
        vars: null
      loop.ansible.builtin.pip: []

- name: openwrt-pip.install|append _params attrs
  ansible.utils.update_fact:
    updates:
      - path: "_params.proxy"
        value: "{{ pip_installer.proxy | default('https://pypi.example.com/simple',true) }}"
      - path: "_params.include.role"
        value: "{{ pip_installer.include.role | default(_params.include.role,true) }}"
      - path: "_params.include.vars"
        value: "{{ pip_installer.include.vars | default(_params.include.vars,true) }}"
      - path: "_params['loop.ansible.builtin.pip']"
        value: "{{ pip_installer['loop.ansible.builtin.pip'] | default(_params['loop.ansible.builtin.pip'],true) }}"
  register: pip_install

# pip configed

- vars:
    pipconfig_dir: "~/.config/pip"
    pipconfig_dir_mode: '0755'
    pipconfig_extra_index_urls: []
    pipconfig_file: "pip.conf"
    pipconfig_file_mode: '0644'
    pipconfig_find_links_urls: []
    pipconfig_index_url: ""
    pipconfig_timeout: 10
    pipconfig_template_file: "pip.conf"
    pipconfig_pip_upgrade: before
    pipconfig_pip_virtualenv: ""
    pipconfig_pip_cmd: "python -m pip"
    pipconfig_pip_level: user
    pipconfig_pip_options:
      global.index-url: "{{ pip_install._params.proxy }}"
  block:
  - name: openwrt-pip.install|pip|include vars
    when: pip_install._params.include.vars | default(None,true) != None
    ansible.builtin.include_vars:
      file: "{{ pip_install._params.include.vars }}"

  - name: openwrt-pip.install|pip|include role
    ansible.builtin.include_role:
      name: "{{ pip_install._params.include.role }}"

# pip package installed

- block:
  - name: openwrt-pip.install|pip|install setuptools(for ansible.builtin.pip)<81(for ansible-core 2.15)
    community.openwrt.command:
      cmd: "python -m pip install --upgrade 'setuptools<81'"
    # On Openwrt 24 `Found existing installation: setuptools None`
    ignore_errors: true

  - name: openwrt-pip.install|pip|install packages
    loop: "{{ pip_install._params['loop.ansible.builtin.pip'] }}"
    ansible.builtin.pip:
      break_system_packages: "{{ item.break_system_packages | default(omit,true) }}"
      chdir: "{{ item.chdir | default(omit,true) }}"
      executable: "{{ item.executable | default(omit,true) }}"
      extra_args: "{{ item.extra_args | default(omit,true) }}"
      name: "{{ item.name | default(omit,true) }}"
      requirements: "{{ item.requirements | default(omit,true) }}"
      state: "{{ item.state | default(omit,true) }}"
      umask: "{{ item.umask | default(omit,true) }}"
      version: "{{ item.version | default(omit,true) }}"
      virtualenv: "{{ item.virtualenv | default(omit,true) }}"
      virtualenv_command: "{{ item.virtualenv_command | default(omit,true) }}"
      virtualenv_python: "{{ item.virtualenv_python | default(omit,true) }}"
      virtualenv_site_packages: "{{ item.virtualenv_site_packages | default(omit,true) }}"
    retries: 3
