#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: docker
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: stat tailscale run
      ansible.builtin.stat:
        path: "/var/run/tailscale"
      register: tailscale_run_stat

    - name: fact template vars
      when: tailscale_run_stat.stat.exists
      ansible.builtin.set_fact:
        caddy_template_volumes:
          - /var/run/tailscale:/var/run/tailscale

    - name: deploy compose
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.deploy.yml"
      vars:
        compose:
          name: caddy
          vars: "{{ caddy | default({},true) }}"
          default:
            files:
              - src: "{{ playbook_dir }}/config/Caddyfile"
                dest: "{{ workpath.remote.full }}/bind_file-Caddyfile"
            volumes:
              - name: external_vol-caddy-data
                driver: local
              - name: external_vol-caddy-config
                driver: local
            envs:
              - file: external_env-all.env
                content: ''
            composes:
              - file: docker-compose.yml
                template: "{{ playbook_dir }}/docker-compose.yml.j2"
                vars:
                  VOLUMES: "{{ caddy_template_volumes if (tailscale_run_stat.stat.exists) else [] }}"
                  NETWORKS: []
                  PORTS:
                    - 80:80
                    - 443:443
                    - 443:443/udp
                    - 2019:2019
