#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: docker
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: deploy compose
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.deploy.yml"
      vars:
        compose:
          vars: "{{ shinobi | default({},true) }}"
          default:
            volumes:
              - name: external_vol-shinobi-config
                driver: local
              - name: external_vol-shinobi-customAutoLoad
                driver: local
              - name: external_vol-shinobi-database
                driver: local
              - name: external_vol-shinobi-videos
                driver: local
              - name: external_vol-shinobi-plugins
                driver: local
              - name: external_vol-shinobi-tensorflow
                driver: local
            envs:
              - file: external_env-shinobi.env
                content: ''
              # - file: external_env-tf.env
              #   content: ''
            composes:
              - file: docker-compose.yml
                template: "{{ playbook_dir }}/docker-compose.yml"
