version: "3.8"

volumes:
  config:
    name: external_vol-shinobi-config
    external: true
  customAutoLoad:
    name: external_vol-shinobi-customAutoLoad
    external: true
  database:
    name: external_vol-shinobi-database
    external: true
  videos:
    name: external_vol-shinobi-videos
    external: true
  plugins:
    name: external_vol-shinobi-plugins
    external: true
  tensorflow:
    name: external_vol-shinobi-tensorflow
    external: true

services:
  shinobi:
    image: registry.gitlab.com/shinobi-systems/shinobi:dev
    env_file: external_env-shinobi.env
    volumes:
      - config:/config
      - database:/var/lib/mysql
      - videos:/home/Shinobi/videos
      - plugins:/home/Shinobi/plugins
      - customAutoLoad:/home/Shinobi/libs/customAutoLoad
      - /dev/shm/Shinobi/streams:/dev/shm/streams
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8580:8080
    container_name: shinobi
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 60s
      timeout: 10s
      retries: 10
      start_period: 10m

  # shinobi-tensorflow:
  #   image: registry.gitlab.com/shinobi-systems/docker-plugin-tensorflow.js:master
  #   env_file: external_env-tf.env
  #   environment:
  #     PLUGIN_HOST: shinobi
  #     PLUGIN_PORT: 8080
  #   volumes:
  #     - tensorflow:/config
  #   container_name: shinobi-tensorflow
  #   restart: unless-stopped
  #   healthcheck:
  #     test: netstat -ltn | grep -c 8082 || exit 1
  #     interval: 60s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 10m
