# code: language=ansible
---

- rescue:
  - name: headscale-node.create|rescue|fail
    when:
      - node is defined
      - node.nodes is defined
      - node.nodes.values() | select() | length > 0
    ansible.builtin.fail:
      msg: "create node fail. exclude param eval."

  block:
  - name: headscale-node.create|assert param
    ansible.builtin.assert:
      that:
        - node is defined
        - node.nodes is defined
        - node.nodes.values() | select() | length > 0
      msg: "var eval fail 'node'"
      quiet: true

  - name: headscale-node.create|fact param
    ansible.builtin.set_fact:
      _node: "{{ node }}"

  - name: headscale-node.create|fact commands
    vars:
      command: "headscale node register --key {{ item.value }} -u {{ _node.user }}"
      dict: "{{ _node.commands | default({},true) }}"
      attr:
        commands: "{{ dict | combine({item.key: command}) }}"
    loop: "{{ _node.nodes | dict2items }}"
    ansible.builtin.set_fact:
      _node: "{{ _node | combine(attr, recursive=True) }}"

  - name: headscale-node.create|wait container
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.wait.yml"
    vars:
      container:
        name: headscale
        until:
          - container_info.exists
        retries: 60
        delay: 60

  - name: headscale-node.create|exec container
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.exec.yml"
    vars:
      container:
        container: headscale
        command: "{{ _node.commands.values() }}"
        register: container_exec

  - name: headscale-node.create|fact results
    vars:
      command: "{{ item.item | b64decode }}"
      match_command_item: "{{ _node.commands | dict2items | selectattr('value','equalto',command) | first }}"
      index: "{{ match_command_item.key }}"
      key: "{{ item.stdout_lines[-1] }}"
      dict: "{{ _node.results | default({},true) }}"
      attr:
        results: "{{ dict | combine({index: key}) }}"
    loop: "{{ container_exec.results }}"
    ansible.builtin.set_fact:
      _node: "{{ _node | combine(attr, recursive=True) }}"

  - name: headscale-node.create|append list
    when: list | type_debug == 'list'
    vars:
      append:
        user: "{{ _node.user }}"
        key: "{{ _node.results }}"
      list: "{{ lookup('ansible.builtin.vars', _node.append) }}"
    ansible.builtin.set_fact:
      "{{ _node.append }}": "{{ list + [append] }}"

  - name: headscale-node.create|append dict
    when: dict | type_debug == 'dict'
    vars:
      dict: "{{ lookup('ansible.builtin.vars', _node.append) }}"
    ansible.builtin.set_fact:
      "{{ _node.append }}": "{{ dict | combine({_node.user: _node.results}) }}"

  - name: headscale-node.create|print exec
    vars:
      docker_hostvars: "{{ hostvars | dict2items
        | selectattr('key','in',groups['docker'])
        | selectattr('value.container_exec','defined') }}"
    ansible.builtin.pause:
      seconds: 1
      prompt: |
        {% for host in docker_hostvars %}

        [{{ host.key }}] =>
        --------------------------------------------------
        {% for item in host.value.container_exec.results %}
        {{ item.stdout | default('',true) }}
        {{ item.stderr | default('',true) }}
        {% endfor %}
        {% endfor %}
