#!/usr/bin/env -S ansible-playbook -k -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: use
  hosts: windows
  tasks:

    - name: test mise
      ansible.windows.win_command:
        cmd: mise --version
        chdir: "{{ mise.home | default('%USERPROFILE%/.mise') }}/bin"
      register: mise_version

    - name: print mise
      vars:
        windows_hostvars: "{{ hostvars | dict2items
          | selectattr('key','in',ansible_play_hosts)
          | selectattr('value.mise_version.skipped','equalto',false) }}"
      ansible.builtin.pause:
        seconds: 1
        prompt: |
          {% for host in windows_hostvars %}

          [{{ host.key }}] =>
          --------------------------------------------------
          {{ host.value.mise_version.stdout | default('',true) }}
          {{ host.value.mise_version.stderr | default('',true) }}
          {% endfor %}

    - name: use sdk
      loop: "{{ mise.sdk }}"
      ansible.windows.win_command:
        cmd: "mise use {{ item }}"
