#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: docker
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: deploy container
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.deploy.yml"
      vars:
        container:
          vars: "{{ srs | default({},true) }}"
          default:
            container:
              detach: true
              restart_policy: always
              ports:
                - 2022:2022
                - 2443:2443
                - 1935:1935
                - 8000:8000/udp
                - 10080:10080/udp
              hostname: srs
              name: srs
              image: ossrs/srs-stack:5
