#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: config
  hosts: openwrt
  tasks:

    - name: set by name
      become: true
      loop: "{{ sysctl }}"
      when: item.name is defined
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      ignore_errors: true

    - name: set by path
      become: true
      loop: "{{ sysctl }}"
      when: item.path is defined
      ansible.builtin.shell: "echo {{ item.value }} | tee {{ item.path }}"
      ignore_errors: true
