#!/usr/bin/env -S ansible-playbook -k -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: install
  hosts: windows
  tasks:

    - name: test jabba
      ansible.windows.win_command:
        cmd: jabba --version
        chdir: "{{ jabba.home | default('%USERPROFILE%/.jabba') }}/bin"
      register: jabba_version

    - name: print jabba
      vars:
        windows_hostvars: "{{ hostvars | dict2items
          | selectattr('key','in',ansible_play_hosts)
          | selectattr('value.jabba_version.skipped','equalto',false) }}"
      ansible.builtin.pause:
        seconds: 1
        prompt: |
          {% for host in windows_hostvars %}

          [{{ host.key }}] =>
          --------------------------------------------------
          {{ host.value.jabba_version.stdout | default('',true) }}
          {{ host.value.jabba_version.stderr | default('',true) }}
          {% endfor %}

    - name: install jdk
      loop: "{{ jabba.jdk }}"
      ansible.windows.win_command:
        cmd: "jabba install {{ item }}"
        chdir: "{{ jabba.home | default('%USERPROFILE%/.jabba') }}/bin"
