# code: language=ansible
---

- rescue:
  - name: headscale-preauthkey.build|rescue|fail
    when:
      - preauthkey is defined
      - preauthkey.data.keys() | length > 0
    ansible.builtin.fail:
      msg: "build preauthkey fail. exclude param eval."

  block:
  - name: headscale-preauthkey.build|assert param
    ansible.builtin.assert:
      that:
        - preauthkey is defined
        - preauthkey.data.keys() | length > 0
      msg: "var eval fail 'preauthkey'"
      quiet: true
  
  - name: headscale-preauthkey.build|fact param
    vars:
      default:
        dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/headscale/preauthkey.yml"
        src: "{{ playbook_dir }}/inventory.yml.j2"
    ansible.builtin.set_fact:
      _preauthkey: "{{ default | combine(preauthkey, recursive=True) }}"

  - name: headscale-preauthkey.build|mkdir inventory
    delegate_to: localhost
    ansible.builtin.file:
      state: directory
      path: "{{ _preauthkey.dest | dirname }}"

  - name: headscale-preauthkey.build|template inventory
    delegate_to: localhost
    vars:
      dest: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}/headscale/preauthkey.yml"
      VARS:
        headscale_preauthkeys: "{{ _preauthkey.data }}"
    ansible.builtin.template:
      src: "{{ _preauthkey.src }}"
      dest: "{{ _preauthkey.dest }}"
