#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: disable
  hosts: wsl
  become: true
  gather_facts: false
  tasks:

    - name: disable wsl conf
      vars:
        conf:
          list:
            - section: interop
              option: appendWindowsPath
              value: 'false'
          shutdown: true
      include_tasks: ../../ansible-tasks/seed-wsl/wsl-conf.change.yml
