#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: link
  hosts: wsl
  become: false
  gather_facts: true
  tasks:

    - name: link wsl ssh
      include_tasks: ../../ansible-tasks/seed-wsl/wsl-profile-ssh.link.yml
