version: "3.8"

volumes:
  config:
    name: external_vol-wechat-config
    external: true

services:
  wechat-selkies:
    image: nickrunning/wechat-selkies:latest   # or ghcr.io/nickrunning/wechat-selkies:latest
    env_file: external_env-all.env
    environment:
      - PUID=1000                    # user ID
      - PGID=100                     # group ID
      # - TZ=Asia/Shanghai             # timezone
      # - LC_ALL=zh_CN.UTF-8           # locale
      # - AUTO_START_WECHAT=true       # default is true
      # - AUTO_START_QQ=false          # default is false
      # - CUSTOM_USER=<Your Name>      # recommended to set a custom user name
      # - PASSWORD=<Your Password>     # recommended to set a password for selkies web ui
    container_name: wechat-selkies
    ports:
      - 3000       # http port
      - 3001       # https port
    restart: unless-stopped
    volumes:
      - config:/config
    # devices:
    #   - /dev/dri:/dev/dri # optional, for hardware acceleration
