# jenkins core
# http://jenkins.home/manage/credentials/
credentials:
  system:
    domainCredentials:
    - credentials:
      # - usernamePassword:
      #     description: "ubuntu@passwd.jenkins.server"
      #     id: "ubuntu@passwd.jenkins.server"
      #     password: ""
      #     scope: GLOBAL
      #     username: "ubuntu"
      # - usernamePassword:
      #     description: "admin@passwd.gitlab.home"
      #     id: "admin@passwd.gitlab.home"
      #     password: ""
      #     scope: GLOBAL
      #     username: "admin"
      # - gitLabApiTokenImpl:
      #     apiToken: ""
      #     description: "admin@token.gitlab.home"
      #     id: "admin@token.gitlab.home"
      #     scope: GLOBAL
      # - string:
      #     description: "admin@secret.sonarqube.home"
      #     id: "admin@secret.sonarqube.home"
      #     scope: GLOBAL
      #     secret: ""

jenkins:
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # Agents -> Agent protocols
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # Authentication -> Authorization
  authorizationStrategy:
    projectMatrix:
      entries:
      - group:
          name: "authenticated"
          permissions:
          - "Credentials/Create"
          - "Credentials/View"
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Create"
          - "Job/Discover"
          - "Job/Read"
          - "Job/Workspace"
          - "Overall/Read"
          - "Run/Replay"
          - "View/Create"
          - "View/Read"
      - user:
          name: "anonymous"
          permissions:
          - "Overall/Read"
          - "Job/Discover"
          - "Job/Read"
          - "View/Read"
      - userOrGroup:
          name: "admin"
          permissions:
          - "Agent/Build"
          - "Agent/Configure"
          - "Agent/Connect"
          - "Agent/Create"
          - "Agent/Delete"
          - "Agent/Disconnect"
          - "Credentials/Create"
          - "Credentials/Delete"
          - "Credentials/ManageDomains"
          - "Credentials/Update"
          - "Credentials/View"
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Configure"
          - "Job/Create"
          - "Job/Delete"
          - "Job/Discover"
          - "Job/Move"
          - "Job/Read"
          - "Job/Workspace"
          - "Overall/Administer"
          - "Overall/Read"
          - "Run/Delete"
          - "Run/Replay"
          - "Run/Update"
          - "SCM/Tag"
          - "View/Configure"
          - "View/Create"
          - "View/Delete"
          - "View/Read"
      - user:
          name: "jenkins"
          permissions:
          - "Overall/Read"
          - "Agent/Build"
          - "Agent/Connect"
          - "Agent/Create"
          - "Credentials/Create"
          - "Credentials/ManageDomains"
          - "Credentials/View"
          - "Job/Build"
          - "Job/Cancel"
          - "Job/Create"
          - "Job/Discover"
          - "Job/Read"
          - "Job/Workspace"
          - "Run/Replay"
          - "SCM/Tag"
          - "View/Create"
          - "View/Read"
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # CSRF Protection -> Crumb Issuer
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # Authentication -> Disable “Keep me signed in”
  disableRememberMe: false
  # jenkins core
  # http://jenkins.home/manage/configure
  # Administrative monitors configuration
  disabledAdministrativeMonitors:
  - "hudson.util.DoubleLaunchChecker"
  # jenkins core
  # http://jenkins.home/label/built-in/
  labelAtoms:
  - name: "built-in"
  - name: "docker"
  - name: "linux"
  # - name: "jenkins01"
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # Markup Formatter
  markupFormatter: "plainText"
  # https://plugins.jenkins.io/antisamy-markup-formatter/
  # http://jenkins.home/manage/configureSecurity
  # Markup Formatter
  # markupFormatter:
  #   rawHtml:
  #     disableSyntaxHighlighting: true
  # jenkins core
  # http://jenkins.home/manage/configure
  # Usage
  mode: EXCLUSIVE
  # http://jenkins.home/me/my-views/view/all/
  myViewsTabBar: "standard"
  # http://jenkins.home/manage/computer/configure
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  # http://jenkins.home/manage/computer/
  nodes:
  # - permanent:
  #     labelString: "linux docker"
  #     launcher:
  #       ssh:
  #         credentialsId: "ubuntu@passwd.jenkins.server"
  #         host: "jenkins01.home"
  #         javaPath: "/usr/bin/java"
  #         port: 22
  #         sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
  #     mode: NORMAL
  #     name: "jenkins01"
  #     nodeProperties:
  #     - toolLocation:
  #         locations:
  #         - home: "git"
  #           key: "hudson.plugins.git.GitTool$DescriptorImpl@Default"
  #         - home: "/home/ubuntu/.sdkman/candidates/java/8.0.265-open"
  #           key: "hudson.model.JDK$DescriptorImpl@8"
  #         - home: "/home/ubuntu/.sdkman/candidates/java/17.0.5-tem"
  #           key: "hudson.model.JDK$DescriptorImpl@17"
  #         - home: "/home/ubuntu/.sdkman/candidates/gradle/6.5"
  #           key: "hudson.plugins.gradle.GradleInstallation$DescriptorImpl@6.5"
  #         - home: "/home/ubuntu/.sdkman/candidates/gradle/7.6"
  #           key: "hudson.plugins.gradle.GradleInstallation$DescriptorImpl@7.6"
  #         - home: "/home/ubuntu/.sdkman/candidates/maven/3.6.3"
  #           key: "hudson.tasks.Maven$MavenInstallation$DescriptorImpl@3.6.3"
  #         - home: "/home/ubuntu/.sdkman/candidates/maven/3.8.7"
  #           key: "hudson.tasks.Maven$MavenInstallation$DescriptorImpl@3.8.7"
  #         - home: "/home/ubuntu/.nvm/versions/node/v16.19.0"
  #           key: "jenkins.plugins.nodejs.tools.NodeJSInstallation$DescriptorImpl@16.19.0"
  #         - home: "/home/ubuntu/.nvm/versions/node/v18.13.0"
  #           key: "jenkins.plugins.nodejs.tools.NodeJSInstallation$DescriptorImpl@18.13.0"
  #         - home: "/home/ubuntu/.pyenv/versions/3.8.13/bin/python"
  #           key: "jenkins.plugins.shiningpanda.tools.PythonInstallation$DescriptorImpl@3.8.13"
  #         - home: "/home/ubuntu/.pyenv/versions/3.10.3/bin/python"
  #           key: "jenkins.plugins.shiningpanda.tools.PythonInstallation$DescriptorImpl@3.10.3"
  #         - home: "/home/ubuntu/.sonar_scanner/sonar-scanner-5.0.1.3006-linux"
  #           key: "hudson.plugins.sonar.SonarRunnerInstallation$DescriptorImpl@5.0.1.3006"
  #     numExecutors: 49
  #     remoteFS: "/home/ubuntu/.jenkins_remote"
  #     retentionStrategy: "always"
  # jenkins core
  # http://jenkins.home/manage/configure
  # # of executors
  numExecutors: 2
  # http://jenkins.home/view/all/
  primaryView:
    all:
      name: "all"
  # jenkins core
  # http://jenkins.home/manage/configure
  # Restrict project naming -> Naming Strategy
  projectNamingStrategy: "standard"
  # jenkins core
  # http://jenkins.home/manage/configure
  # Quiet period
  quietPeriod: 5
  # https://www.jenkins.io/doc/book/security/controller-isolation/jep-235/
  remotingSecurity:
    enabled: true
  # jenkins core
  # http://jenkins.home/manage/configure
  # SCM checkout retry count
  scmCheckoutRetryCount: 0
  # jenkins core
  # http://jenkins.home/manage/configure
  # Labels
  labelString: ""
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # Authentication -> Security Realm
  securityRealm:
    local:
      allowsSignup: true
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        # - "userCommunityProperty"
        - "consoleUrlProvider"
        - "mailer"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
      - id: "jenkins"
        name: "jenkins"
        password: jenkins.123
        properties:
        - "apiToken"
        # - "userCommunityProperty"
        - "consoleUrlProvider"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "jenkins@mail.home"
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # Agents -> TCP port for inbound agents
  slaveAgentPort: 50000
  # jenkins core
  # http://jenkins.home/manage/configure
  # System Message
  systemMessage: "Self-registered users, default user: jenkins:jenkins.123"
  # jenkins core
  # http://jenkins.home/manage/pluginManager/advanced
  # Update Site
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  # http://jenkins.home/view/all/
  views:
  - all:
      name: "all"
  # https://plugins.jenkins.io/dashboard-view/
  - dashboard:
      bottomPortlets:
      - statBuilds:
          name: "Build statistics"
      - statJobs:
          name: "Job statistics"
      - statSlaves:
          name: "Agent statistics"
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      # - "builtOnColumn"
      # - "coverageColumn"
      includeRegex: ".*"
      name: "statistics"
      recurse: true
      topPortlets:
      - latestBuilds:
          name: "Latest builds"
          numBuilds: 10
      - unstableJobsPortlet:
          name: "Unstable Jobs"
          recurse: false
          showOnlyFailedJobs: false
  # http://jenkins.home/view/all/
  viewsTabBar: "standard"

# jenkins core
# http://jenkins.home/manage/configureCredentials/
# Credential Providers
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"

# jenkins core
# http://jenkins.home/manage/appearance/
# Appearance
appearance:
  prism:
    theme: PRISM

security:
  # jenkins core
  # http://jenkins.home/manage/configureSecurity
  # API Token
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  # https://plugins.jenkins.io/copyartifact/
  # http://jenkins.home/manage/configureSecurity
  # Copy Artifact
  copyartifact:
    mode: MIGRATION
  # https://plugins.jenkins.io/git/
  # http://jenkins.home/manage/configureSecurity
  # Git Hooks
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  # https://plugins.jenkins.io/git-client/
  # http://jenkins.home/manage/configureSecurity
  # Git Host Key Verification Configuration
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  # https://plugins.jenkins.io/job-dsl/
  # http://jenkins.home/manage/configureSecurity
  # Enable script security for Job DSL scripts
  # globalJobDslSecurityConfiguration:
  #   useScriptSecurity: false
  # https://plugins.jenkins.io/authorize-project/ 
  # http://jenkins.home/manage/configureSecurity
  # Authorization Access Control for Builds
  # queueItemAuthenticator:
  #   authenticators:
  #   - global:
  #       strategy: "systemAuthorizationStrategy"
  # https://plugins.jenkins.io/sshd/
  # http://jenkins.home/manage/configureSecurity
  # SSH Server
  sSHD:
    port: -1
  # https://plugins.jenkins.io/script-security/
  # http://jenkins.home/manage/scriptApproval/
  # Signatures already approved:
  scriptApproval:
    approvedSignatures:
    - "method groovy.lang.GroovyObject getProperty java.lang.String"
    - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"
    - "method hudson.model.Cause$UpstreamCause getUpstreamProject"
    - "method hudson.model.ItemGroup getItem java.lang.String"
    - "method hudson.model.Run getCause java.lang.Class"
    - "method hudson.plugins.git.BranchSpec getName"
    - "method hudson.plugins.git.GitSCM getBranches"
    - "method hudson.plugins.git.GitSCM getUserRemoteConfigs"
    - "method hudson.plugins.git.UserRemoteConfig getCredentialsId"
    - "method hudson.plugins.git.UserRemoteConfig getUrl"
    - "method java.io.File exists"
    - "method java.io.File getAbsolutePath"
    - "method java.io.File getName"
    - "method java.io.File isDirectory"
    - "method java.io.File isHidden"
    - "method java.io.File listFiles"
    - "method org.jenkinsci.plugins.workflow.support.actions.EnvironmentAction getEnvironment"
    - "method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild"
    - "new groovy.util.AntBuilder"
    - "new java.io.File java.lang.String"
    - "staticMethod jenkins.model.Jenkins get"
    - "staticMethod jenkins.model.Jenkins getInstance"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods renameTo java.io.File java.lang.String"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods reverse java.util.List"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object java.lang.String"

unclassified:
  # https://plugins.jenkins.io/build-discarder/
  # http://jenkins.home/manage/configure
  # Global Build Discarders
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
    - simpleBuildDiscarder:
        discarder:
          logRotator:
            artifactDaysToKeepStr: "30"
            artifactNumToKeepStr: "60"
            daysToKeepStr: "30"
            numToKeepStr: "60"
  # https://plugins.jenkins.io/build-timeout/
  # http://jenkins.home/manage/configure
  # Build-timeout Plugin > BuildStep Action
  buildStepOperation:
    enabled: false
  # https://plugins.jenkins.io/email-ext/
  # http://jenkins.home/manage/configure
  # Extended E-mail Notification
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  # https://plugins.jenkins.io/gradle/
  # http://jenkins.home/manage/configure
  # Develocity Build Scans
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  # jenkins core
  # http://jenkins.home/manage/configure
  # Fingerprints
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  # https://plugins.jenkins.io/github-branch-source/
  # http://jenkins.home/manage/configure
  # GitHub API usage
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  # https://plugins.jenkins.io/github/
  # http://jenkins.home/manage/configure
  # GitHub
  gitHubPluginConfig:
    hookUrl: "http://jenkins.home/github-webhook/"
  # https://plugins.jenkins.io/gitlab-plugin/
  # http://jenkins.home/manage/configure
  # GitLab
  gitLabConnectionConfig:
    connections:
    - apiTokenId: "admin@token.gitlab.home"
      clientBuilderId: "autodetect"
      connectionTimeout: 10
      ignoreCertificateErrors: false
      name: "default"
      readTimeout: 10
      url: "http://gitlab.home"
    useAuthenticatedEndpoint: true
  # https://plugins.jenkins.io/build-timeout/
  # http://jenkins.home/manage/configure
  # Global Build Time Out
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  # https://plugins.jenkins.io/gradle/
  # http://jenkins.home/manage/configure
  # Develocity integration
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  # https://plugins.jenkins.io/cloudbees-folder/
  # http://jenkins.home/manage/configure
  # Folder
  defaultFolderConfiguration:
    healthMetrics:
    - worstChildHealthMetric:
        recursive: true
  # https://plugins.jenkins.io/junit/
  # MISSING
  junitTestResultStorage:
    storage: "file"
  # jenkins core
  # http://jenkins.home/manage/configure
  # Jenkins Location
  location:
    adminAddress: "NONE <nobody@nowhere>"
    url: "http://jenkins.home/"
  # https://plugins.jenkins.io/mailer/
  # http://jenkins.home/manage/configure
  # E-mail Notification
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  # https://plugins.jenkins.io/maven-plugin
  # http://jenkins.home/manage/configure
  # Maven Project Configuration
  # mavenModuleSet:
  #   localRepository: "default"
  # MISSING
  # https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/configuring-max-polling-threads
  pollSCM:
    pollingThreadCount: 10
  # https://plugins.jenkins.io/git/
  # http://jenkins.home/manage/configure
  # Git plugin
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  # https://plugins.jenkins.io/sonar/
  # http://jenkins.home/manage/configure
  # SonarQube servers
  # sonarGlobalConfiguration:
  #   buildWrapperEnabled: true
  #   installations:
  #   - credentialsId: "secret.sonarqube.home"
  #     name: "default"
  #     serverUrl: "http://sonarqube.home"
  #     triggers:
  #       skipScmCause: false
  #       skipUpstreamCause: false
  # https://plugins.jenkins.io/publish-over-ssh/
  # http://jenkins.home/manage/configure
  # Publish over SSH
  # sshPublisher:
  #   commonConfig:
  #     disableAllExec: false
  #     encryptedPassphrase: ""
  # https://plugins.jenkins.io/subversion/
  # http://jenkins.home/manage/configure
  # Subversion
  subversionSCM:
    workspaceFormat: 8
  # https://plugins.jenkins.io/timestamper/
  # http://jenkins.home/manage/configure
  # Timestamper
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  # https://plugins.jenkins.io/copyartifact/
  # http://jenkins.home/manage/configure
  # Copyartifact: Upstream build that triggered this job
  upstream:
    globalUpstreamFilterStrategy: UseOldest

# jenkins core
# http://jenkins.home/manage/configureTools/
tool:
  # mavenGlobalConfig:
  #   globalSettingsProvider: "standard"
  #   settingsProvider: "standard"
  # dockerTool:
  #   installations:
  #   - home: "docker"
  #     name: "default"
  # git:
  #   installations:
  #   - home: "git"
  #     name: "Default"
  # gradle:
  #   installations:
  #   - home: "/home/jenkins/.sdkman/candidates/gradle/6.5"
  #     name: "6.5"
  #   - home: "/home/jenkins/.sdkman/candidates/gradle/7.6"
  #     name: "7.6"
  # jdk:
  #   installations:
  #   - home: "/home/jenkins/.sdkman/candidates/java/8.0.265-open"
  #     name: "8"
  #   - home: "/home/jenkins/.sdkman/candidates/java/17.0.5-tem"
  #     name: "17"
  # maven:
  #   installations:
  #   - home: "/home/jenkins/.sdkman/candidates/maven/3.6.3"
  #     name: "3.6.3"
  #   - home: "/home/jenkins/.sdkman/candidates/maven/3.8.7"
  #     name: "3.8.7"
  # nodejs:
  #   installations:
  #   - home: "/home/jenkins/.nvm/versions/node/v16.19.0"
  #     name: "16.19.0"
  #   - home: "/home/jenkins/.nvm/versions/node/v18.13.0"
  #     name: "18.13.0"
  # powerShellInstallation:
  #   installations:
  #   - home: "powershell.exe"
  #     name: "DefaultWindows"
  #   - home: "pwsh"
  #     name: "DefaultLinux"
  # pythonInstallation:
  #   installations:
  #   - home: "/home/jenkins/.pyenv/versions/3.8.13"
  #     name: "3.8.13"
  #   - home: "/home/jenkins/.pyenv/versions/3.10.3"
  #     name: "3.10.3"
  # sonarRunnerInstallation:
  #   installations:
  #   - home: "/home/jenkins/.sonar_scanner/sonar-scanner-5.0.1.3006-linux"
  #     name: "5.0.1.3006"