#!/usr/bin/env -S ansible-playbook -k -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: install
  hosts: windows
  tasks:

    - name: install package
      loop: "{{ chocolatey.packages | default([],true) }}"
      vars:
        combine:
          state: present
        args: "{{ item | combine(combine, recursive=True) }}"
      chocolatey.chocolatey.win_chocolatey: "{{ args }}"
      register: package_install
      until: package_install is succeeded

    - name: install group config
      vars:
        group_names: "{{ chocolatey.groups | default([],true) }}"
        group_vars: "{{ chocolatey_groups | default({},true)
          | dict2items
          | selectattr('key','in',group_names)
          | selectattr('value.packages','defined')
          | map(attribute='value.packages')
          | flatten }}"
        combine:
          state: present
        args: "{{ item | combine(combine, recursive=True) }}"
      loop: "{{ group_vars }}"
      chocolatey.chocolatey.win_chocolatey: "{{ args }}"
      register: package_install
      until: package_install is succeeded
