#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: docker
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - when: ngrok.token is defined
      block:
      - name: deploy compose
        include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.deploy.yml"
        vars:
          compose:
            name: ngrok
            vars: "{{ ngrok | default({},true) }}"
            default:
              envs:
                - file: external_env-all.env
                  content: |
                    NGROK_AUTHTOKEN={{ ngrok.token }}
              composes:
                - file: docker-compose.yml
                  template: "{{ playbook_dir }}/docker-compose.yml.j2"
                  vars:
                    COMMAND: "http 80"

    - when: ngrok.config is defined
      block:
      - name: deploy compose
        include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.deploy.yml"
        vars:
          compose:
            name: ngrok
            vars: "{{ ngrok | default({},true) }}"
            default:
              files:
                - src: "{{ ngrok.config }}"
                  dest: "{{ workpath.remote.full }}/ngrok.yml"
              volumes:
                - name: external_vol-ngrok-config
                  driver: local
                  push:
                    - src: "{{ workpath.remote.full }}/ngrok.yml"
                      dest: "ngrok.yml"
              envs:
                - file: external_env-all.env
                  content: |
                    NGROK_CONFIG=/home/ngrok/.config/ngrok/ngrok.yml
              composes:
                - file: docker-compose.yml
                  template: "{{ playbook_dir }}/docker-compose.yml.j2"
                  vars:
                    COMMAND: "start --all"

    - when:
        - ngrok is defined
        - ngrok.token is undefined
        - ngrok.config is undefined
      block:
      - name: deploy compose
        include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.deploy.yml"
        vars:
          compose:
            name: ngrok
            vars: "{{ ngrok | default({},true) }}"
            default:
              files:
                - src: "{{ playbook_dir }}/config/ngrok.yml"
                  dest: "{{ workpath.remote.full }}/ngrok.yml"
              volumes:
                - name: external_vol-ngrok-config
                  driver: local
                  push:
                    - src: "{{ workpath.remote.full }}/ngrok.yml"
                      dest: "ngrok.yml"
              envs:
                - file: external_env-all.env
                  content: |
                    NGROK_CONFIG=/home/ngrok/.config/ngrok/ngrok.yml
              composes:
                - file: docker-compose.yml
                  template: "{{ playbook_dir }}/docker-compose.yml.j2"
                  vars:
                    COMMAND: "start --none"
