version: "3.8"

volumes:
  etc:
    name: shadowsocks-libev-etc

services:
  shadowsocks-libev:
    image: teddysun/shadowsocks-libev:latest
    env_file: external_env-libev.env
    volumes:
      - ./bind_file-libev.json:/etc/shadowsocks-libev/config.json
      - etc:/etc/shadowsocks-libev
    network_mode: "host"
    container_name: shadowsocks-libev
    restart: always
