version: "3.8"

volumes:
  storage:
    name: external_vol-macos-storage
    external: true

services:
  macos:
    image: dockurr/macos:latest
    env_file: external_env-all.env
    environment:
      VERSION: "15"
      # RAM_SIZE: "8G"
      # CPU_CORES: "4"
      # DISK_SIZE: "256G"
      # DHCP: "Y"
      # ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"
    volumes:
      - storage:/storage
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006
      - 5900/tcp
      - 5900/udp
    restart: always
    stop_grace_period: 2m
