version: '3'

services:
  agent:
    image: portainer/agent:latest
    env_file: external_env-all.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    # network_mode: bridge
    container_name: agent
    restart: always
