# code: language=ansible
---

- name: tailscale-cert.deploy|wait container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.wait.yml"
  vars:
    container:
      name: tailscale
      until:
        - container_info.exists
      retries: 60
      delay: 60

- name: tailscale-cert.deploy|fact commands
  loop: "{{ tailscale.certs | default([],true) }}"
  loop_control:
    loop_var: domain
  ansible.builtin.set_fact:
    tailscale_cert_cmds: "tailscale cert {{ domain }}"

- name: tailscale-cert.deploy|exec container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.exec.yml"
  vars:
    container:
      container: tailscale
      command: "{{ tailscale_cert_cmds }}"
      register: container_exec
