version: '3.8'

volumes:
  userdata:
    name: external_vol-domoticz-userdata
    external: true

networks:
  domoticz:

services:
  domoticz:
    image: domoticz/domoticz:2021-beta.13738
    env_file: external_env-all.env
    # environment:
    #   - LOG_PATH=/opt/domoticz/userdata/domoticz.log
    volumes:
      - userdata:/opt/domoticz/userdata
    networks:
      - domoticz
    ports:
      - 8080:8080
    # network_mode: "host"
    container_name: domoticz
    restart: always
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 10m
