#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: linux
  tasks:

    - vars:
        mode: "{{ rclone.mode | default('role',true) }}"
      block:
      - name: role rclone
        when: mode == 'role'
        ansible.builtin.include_role:
          name: stefangweichinger.ansible_rclone

      - when: mode == 'normal'
        block:
        - name: download get rclone
          ansible.builtin.get_url:
            url: "https://rclone.org/install.sh"
            dest: "~/get-rclone.sh"
          register: rclone_get

        - name: shell get rclone
          become: true
          ansible.builtin.shell: "bash {{ rclone_get.dest }}"
          register: rclone_sh
          ignore_errors: true

        - name: print get rclone
          vars:
            linux_hostvars: "{{ hostvars | dict2items
              | selectattr('key','in',ansible_play_hosts)
              | selectattr('value.rclone_sh','defined') }}"
          ansible.builtin.pause:
            seconds: 1
            prompt: |
              {% for host in linux_hostvars %}

              [{{ host.key }}] =>
              --------------------------------------------------
              {{ host.value.rclone_sh.stdout | default('',true) }}
              {{ host.value.rclone_sh.stderr | default('',true) }}
              {% endfor %}

    - name: shell version rclone
      ansible.builtin.shell: rclone --version
      register: rclone_version

    - name: print version rclone
      vars:
        linux_hostvars: "{{ hostvars | dict2items
          | selectattr('key','in',ansible_play_hosts)
          | selectattr('value.rclone_version','defined') }}"
      ansible.builtin.pause:
        seconds: 1
        prompt: |
          {% for host in linux_hostvars %}

          [{{ host.key }}] =>
          --------------------------------------------------
          {{ host.value.rclone_version.stdout | default('',true) }}
          {{ host.value.rclone_version.stderr | default('',true) }}
          {% endfor %}
