#!/usr/bin/env -S ansible-playbook -k -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: add
  hosts: windows
  tasks:

    - name: add ipv4
      loop: "{{ netsh.port_range.excluded.ipv4 | default([],true) }}"
      ansible.windows.win_command: |
        netsh int ipv4 add excludedportrange protocol={{ item.protocol }} startport={{ item.startport }} numberofports={{ item.numberofports }} store={{ item.store }}
      register: range_excluded_add
      until: range_excluded_add is succeeded
      ignore_errors: true

    - name: add group ipv4
      vars:
        group_names: "{{ netsh.groups | default([],true) }}"
        group_vars: "{{ netsh_groups | default({},true)
          | dict2items
          | selectattr('key','in',group_names)
          | selectattr('value.port_range.excluded.ipv4','defined')
          | rejectattr('value.port_range.excluded.ipv4','equalto',None)
          | map(attribute='value.port_range.excluded.ipv4')
          | flatten }}"
      loop: "{{ group_vars }}"
      ansible.windows.win_command: |
        netsh int ipv4 add excludedportrange protocol={{ item.protocol }} startport={{ item.startport }} numberofports={{ item.numberofports }} store={{ item.store }}
      register: range_excluded_add
      until: range_excluded_add is succeeded
      ignore_errors: true

    - name: add ipv6
      loop: "{{ netsh.port_range.excluded.ipv6 | default([],true) }}"
      ansible.windows.win_command: |
        netsh int ipv6 add excludedportrange protocol={{ item.protocol }} startport={{ item.startport }} numberofports={{ item.numberofports }} store={{ item.store }}
      register: range_excluded_add
      until: range_excluded_add is succeeded
      ignore_errors: true

    - name: add group ipv6
      vars:
        group_names: "{{ netsh.groups | default([],true) }}"
        group_vars: "{{ netsh_groups | default({},true)
          | dict2items
          | selectattr('key','in',group_names)
          | selectattr('value.port_range.excluded.ipv6','defined')
          | rejectattr('value.port_range.excluded.ipv6','equalto',None)
          | map(attribute='value.port_range.excluded.ipv6')
          | flatten }}"
      loop: "{{ group_vars }}"
      ansible.windows.win_command: |
        netsh int ipv6 add excludedportrange protocol={{ item.protocol }} startport={{ item.startport }} numberofports={{ item.numberofports }} store={{ item.store }}
      register: range_excluded_add
      until: range_excluded_add is succeeded
      ignore_errors: true
