version: "3.8"

services:
  notifier:
    image: lorcas/docker-telegram-notifier:latest
    env_file: external_env-all.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: "bridge"
    container_name: notifier
    restart: unless-stopped
