#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: docker
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: deploy container
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.deploy.yml"
      vars:
        container:
          vars: "{{ portainer.ce | default({},true) }}"
          default:
            container:
              detach: true
              restart_policy: always
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - portainer_data:/data
              ports:
                - 9000:9000
                - 9443:9443
                - 8000:8000
              hostname: portainer-ce
              name: portainer-ce
              image: portainer/portainer-ce:latest
