#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: openwrt
  tasks:

    - rescue:
      - name: rescue|fail tasks
        when:
          - hostvars[inventory_hostname].cloudflared | default(None) != None
        ansible.builtin.fail:
          msg: "config fail. exclude host var assert."

      block:
      - name: assert host var
        ansible.builtin.assert:
          that:
            - hostvars[inventory_hostname].cloudflared | default(None) != None
          msg: "host var assert fail 'cloudflared'"
          quiet: true
      - block:
        - name: include vars
          when: cloudflared.vars_file is defined
          ansible.builtin.include_vars:
            file: "{{ cloudflared.vars_file }}"

        - name: copy file
          when: cloudflared.cert_file is defined
          community.openwrt.copy:
            src: "{{ cloudflared.cert_file }}"
            dest: /etc/cloudflared/cert.pem

        - name: include cloudflared
          ansible.builtin.include_role:
            name: xiaoyao9184.cloudflare-configured

      - block:
        - name: version cloudflared
          ansible.builtin.command: "cloudflared --version"
          register: cloudflared_version_cli

        - name: print version
          vars:
            linux_hostvars: "{{ hostvars | dict2items
              | selectattr('key','in',ansible_play_hosts)
              | selectattr('value.cloudflared_version_cli','defined') }}"
          ansible.builtin.pause:
            seconds: 1
            prompt: |
              {% for host in linux_hostvars %}

              [{{ host.key }}] =>
              --------------------------------------------------
              {{ host.value.cloudflared_version_cli.stdout | default('',true) }}
              {{ host.value.cloudflared_version_cli.stderr | default('',true) }}
              {% endfor %}
