version: '3.8'

volumes:
  data:
    name: external_vol-grafana-data
    external: true
  dashboards:
    name: external_vol-grafana-dashboards
    external: true
  provisioning:
    name: external_vol-grafana-provisioning
    external: true

networks:
  grafana:

services:
  grafana:
    image: grafana/grafana:latest
    env_file: external_env-all.env
    volumes:
      - data:/var/lib/grafana
      - dashboards:/var/lib/grafana/dashboards
      - provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    networks:
      - grafana
    container_name: grafana
    restart: always
    healthcheck:
      test: nc -z localhost 3000 || exit 1
      interval: 60s
      timeout: 5s
      retries: 10
      start_period: 10m
