# code: language=ansible
---

- name: ct.deploy|assert param
  ansible.builtin.assert:
    that:
      - ct_deployer is defined
    msg: "param undefined 'ct_deployer'"
    quiet: true

- name: ct.deploy|debug param
  ansible.builtin.debug:
    msg: "{{ ct_deployer }}"
    verbosity: 3

# This fact is only as a prototype for update_fact.
# The value will not be updated.
- name: ct.deploy|ensure _param exist
  ansible.builtin.set_fact:
    _param:
      pubkey: {}
      template: {}
      instance: {}
      config: {}
      command: {}

- name: ct.deploy|append _param attrs
  ansible.utils.update_fact:
    updates:
      - path: "_param"
        value: "{{ ct_deployer | default({},true) }}"
  register: ct_deploy

- name: ct.deploy|add pubkey
  when: ct_deploy._param.pubkey | default(None,true) != None
  include_tasks: ../seed/pve-pubkey.add.yml
  vars:
    pubkey_adder: "{{ ct_deploy._param.pubkey }}"

- name: ct.deploy|add template
  when: ct_deploy._param.template | default(None,true) != None
  include_tasks: ../seed/pve-template.add.yml
  vars:
    template_adder: "{{ ct_deploy._param.template }}"

- name: ct.deploy|add instance
  when: ct_deploy._param.instance | default(None,true) != None
  include_tasks: ../seed/pve-instance.add.yml
  vars:
    instance_adder: "{{ ct_deploy._param.instance }}"

- name: ct.deploy|add config
  when: ct_deploy._param.config | default(None,true) != None
  include_tasks: ../seed/pve-config.add.yml
  vars:
    config_adder: "{{ ct_deploy._param.config | combine({'type': 'lxc'}, recursive=True) }}"

- name: ct.deploy|run command
  when: ct_deploy._param.command | default(None,true) != None
  include_tasks: "{{ playbook_dir }}/../../.seed/ansible-tasks/seed-command.run.yml"
  vars:
    command_run: "{{ ct_deploy._param.command }}"
