# code: language=ansible
---

- rescue:
  - name: upsmon.config|rescue|fail tasks
    when:
      - nut is defined
      - vmware is defined
    ansible.builtin.fail:
      msg: "config upsmon fail. exclude var undefined."

  block:
  - name: upsmon.config|assert var
    ansible.builtin.assert:
      that:
        - nut is defined
        - vmware is defined
      msg: "var eval fail {{ nut }} {{ vmware }}"
      quiet: true

  - name: upsmon.config|set upsmon
    loop:
      - esxcli system settings advanced set -o "/UserVars/NutUpsName" --string-value "{{ nut.upsname | default('upsname@nutserver',true) }}"
      - esxcli system settings advanced set -o "/UserVars/NutUser" --string-value "{{ nut.user | default('upsuser',true) }}"
      - esxcli system settings advanced set -o "/UserVars/NutPassword" --string-value "{{ nut.password | default('upspassword',true) }}"
      - esxcli system settings advanced set -o "/UserVars/NutFinalDelay" --int-value "{{ nut.finaldelay | default(5,true) }}"
      - esxcli system settings advanced set -o "/UserVars/NutOnBatteryDelay" --int-value "{{ nut.onnatterydelay | default(0,true) }}"
      - esxcli system settings advanced set -o "/UserVars/NutSendMail" --int-value "{{ nut.sendmail | default(0,true) }}"
      - esxcli system settings advanced set -o "/UserVars/NutMailTo" --string-value "{{ nut.mailto | default('root@domain',true) }}"
      - esxcli system settings advanced set -o "/UserVars/NutMinSupplies" --int-value "{{ nut.minsupplies | default(1,true) }}"
    ansible.builtin.shell:
      cmd: "{{ item }}"

  - name: upsmon.config|on service policy
    delegate_to: localhost
    community.vmware.vmware_host_service_manager:
      hostname: "{{ vmware.hostname }}"
      username: "{{ vmware.username }}"
      password: "{{ vmware.password }}"
      validate_certs: false
      esxi_hostname: '{{ vmware.hostname }}'
      service_name: NutClient
      service_policy: on
      state: present

  - name: upsmon.config|restart upsmon service
    ansible.builtin.shell:
      cmd: "/etc/init.d/upsmon restart"
    register: upsmon_service_restart
