# code: language=ansible
---

- when:
    - download.url | default(None,true) == None
  block:
  - name: upsmon.download|get latest
    ansible.builtin.uri:
      url: "https://api.github.com/repos/rgc2000/NutClient-ESXi/releases/latest"
      return_content: true
    register: upsmon_latest_get

  - name: upsmon.download|fact upsmon_package_download by latest
    vars:
      asset_x86_64_tar_gz: "{{ upsmon_latest_get.json.assets | selectattr('name', 'search', 'x86_64.tar.gz') | first }}"
      asset_offline_bundle_zip: "{{ upsmon_latest_get.json.assets | selectattr('name', 'search', 'offline_bundle.zip') | first }}"
      asset: "{{ (download.mode | default('esxcli',true) == 'esxcli' )
        | ternary(asset_offline_bundle_zip, asset_x86_64_tar_gz) }}"
    ansible.builtin.set_fact:
      upsmon_package_download:
        mode: "{{ download.mode | default('esxcli',true) }}"
        url: "{{ asset.browser_download_url }}"
        file: "~/.esxi/{{ asset.name }}"
        version: "{{ upsmon_latest_get.json.name }}"
    ignore_errors: true

- when:
    - download.url | default(None,true) != None
  block:
  - name: upsmon.download|fact upsmon_package_download by url
    vars:
      filename: "{{ download.url | regex_search('[^\/]+(?=\/$|$)') }}"
    ansible.builtin.set_fact:
      upsmon_package_download:
        mode: "{{ download.mode }}"
        url: "{{ download.url }}"
        file: "~/.esxi/{{ filename }}"
        version: "{{ filename | splitext | first }}"
    ignore_errors: true

- name: upsmon.download|mkdir upsmon dest
  ansible.builtin.file:
    state: directory
    path: "{{ upsmon_package_download.file | dirname }}"

- name: upsmon.download|download upsmon file
  ansible.builtin.get_url:
    dest: "{{ upsmon_package_download.file }}"
    url: "{{ upsmon_package_download.url }}"
