#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: config
  hosts: esxi
  tasks:

    - name: config upsmon
      include_tasks: ansible-tasks.config.yml
      vars:
        config: "{{ nut.config | default(None) }}"

    - name: print test status
      vars:
        esxi_hostvars: "{{ hostvars | dict2items
          | selectattr('key','in',ansible_play_hosts)
          | selectattr('value.upsmon_package_config','defined') }}"
      ansible.builtin.pause:
        seconds: 1
        prompt: |
          {% for host in esxi_hostvars %}

          [{{ host.key }}] =>
          --------------------------------------------------
          {{ host.value.upsmon_package_config.stdout | default('',true) }}
          {{ host.value.upsmon_package_config.stderr | default('',true) }}
          {% endfor %}
