version: "3.8"

networks:
  mediamtx:

services:
  mediamtx:
    image: bluenviron/mediamtx:1.12.0
    env_file: external_env-all.env
    # environment:
    #   - MTX_PATHS_CAM_SOURCE=rpiCamera
    volumes:
      - ./bind_file-mediamtx.yml:/mediamtx.yml
      - /run/udev:/run/udev:ro
    tmpfs:
      - /dev/shm:exec
    privileged: true
    networks:
      - mediamtx
    ports:
      - 8554
      - 8000
      - 8001
      - 1935
      - 8888
      - 8889
      - 8189
      - 8890
    # network_mode: bridge
    container_name: mediamtx
    restart: always
