# code: language=ansible
---

- name: docker-secret.add|debug share
  ansible.builtin.debug:
    verbosity: 3
    var: secret_share

- vars:
    group: "{{ secret_share.group | default('docker-manager',true) }}"
  rescue:

  - name: docker-secret.add|fail tasks
    when: inventory_hostname in groups[group] | default([],true)
    ansible.builtin.fail:
      msg: "add secret fail. exclude wrong group."

  block:
  - name: docker-secret.add|assert defined in group
    ansible.builtin.assert:
      that:
        - inventory_hostname in groups[group] | default([],true)
        - secret is defined
      msg: "var eval fail {{ secret }}"
      quiet: true

  - name: docker-secret.add|fact param
    ansible.builtin.set_fact:
      _secret: "{{ secret }}"

  - rescue:
    - name: docker-secret.add|rescue any other|fail
      when:
        - _secret | default(None) != None
      ansible.builtin.fail:
        msg: "add secret '{{ _secret.name }}' fail, exclude enable any: '{{ secret_share.any | default(false) }}'."

    block:
    - name: docker-secret.add|add by fact
      vars:
        keys_to_remove: ['group','once','any']
        keys_to_keep: "{{ _secret.keys() | difference(keys_to_remove) }}"
        values_to_keep: "{{ keys_to_keep | map('extract', _secret) | list }}"
        secret_remove_key: "{{ dict(keys_to_keep | zip(values_to_keep)) }}"
        secret_merge_label:
          labels:
            "com.docker.stack.namespace": seed
            "com.github.xiaoyao9184.docker-seed.type": "docker-secret.add"
            "com.github.xiaoyao9184.docker-seed.creator": "{{ lookup('ansible.builtin.env', 'SEED_NAME') | default('docker-secret.add',true) }}"
        args: "{{ secret_remove_key | combine(secret_merge_label, recursive=True) }}"
      community.docker.docker_secret: "{{ args }}"

    - name: docker-secret.add|unfact param
      run_once: "{{ secret_share.any | default(false) }}"
      ansible.builtin.set_fact:
        _secret: !!null
