# code: language=ansible
---

- name: docker-secrets.add|debug share
  ansible.builtin.debug:
    verbosity: 3
    var: secrets_share

- name: docker-secrets.add|assert param
  ansible.builtin.assert:
    that:
      - secrets is defined
      - secrets | type_debug == 'list'
    msg: "var eval fail {{ secrets }}"
    quiet: true

- name: docker-secrets.add|fact param
  ansible.builtin.set_fact:
    _secrets: "{{ secrets | flatten }}"

- vars:
    share_mode: "{{ secrets_share.mode | default('index') }}"
    share_group: "{{ secrets_share.group | default('docker',true) }}"
  block:
  - name: docker-secrets.add|index|loop
    loop: "{{ range(0, _secrets | length, 1) | list }}"
    loop_control:
      loop_var: secret_index
    when:
      - share_mode == 'index'
      - inventory_hostname in groups[secret_share.group] | default([],true)
    include_tasks: docker-secret.add.yml
    vars:
      secret: "{{ _secrets[secret_index] }}"
      secret_share:
        any: false
        group: "{{ secret.group | default(share_group,true) }}"

  - name: docker-secrets.add|value|loop
    loop: "{{ _secrets }}"
    loop_control:
      loop_var: secret
    when:
      - share_mode == 'value'
      - inventory_hostname in groups[secret_share.group] | default([],true)
    include_tasks: ../seed-task.once.yml
    vars:
      task_share:
        run_once: "{{ secret.once | default(false) }}"
        task: seed-docker/docker-secret.add.yml
      secret_share:
        any: "{{ secret.any | default(false) }}"
        group: "{{ secret.group | default(share_group,true) }}"

- name: docker-secrets.add|unfact param
  run_once: true
  ansible.builtin.set_fact:
    _secrets: !!null
