# code: language=ansible
---

- name: docker-stack.deploy|fact workpath
  when: workpath.remote is undefined
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

- name: docker-stack.deploy|assert compose
  ansible.builtin.assert:
    that:
      - stack is defined
    msg: "var eval fail {{ stack }}"
    quiet: true

- name: docker-stack.deploy|fact param
  ansible.builtin.set_fact:
    _stack_deploy: "{{ stack }}"

- block:
  - name: docker-stack.deploy|mkdir workpath
    ansible.builtin.file:
      state: directory
      path: "{{ workpath.remote.full }}"

  - name: docker-stack.deploy|push files
    vars:
      files: "{{ _stack_deploy.vars.files | default(files_default,true) }}"
      files_default: "{{ _stack_deploy.default.files | default([],true) }}"
      files_share: "{{ _stack_deploy.share.files | default({},true) }}"
    when: files | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-files.push.yml"

  - name: docker-stack.deploy|init nfs-mounts
    vars:
      mounts: "{{ _stack_deploy.vars.mounts | default(mounts_default,true) }}"
      mounts_default: "{{ _stack_deploy.default.mounts | default({},true) }}"
      mounts_share: "{{ _stack_deploy.share.mounts | default({},true) }}"
    when: mounts | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-nfs/nfs-mounts.init.yml"

  - name: docker-stack.deploy|init volumes
    vars:
      volumes: "{{ _stack_deploy.vars.volumes | default(volumes_default,true) }}"
      volumes_default: "{{ _stack_deploy.default.volumes | default({},true) }}"
      volumes_share: "{{ _stack_deploy.share.volumes | default({},true) }}"
    when: volumes | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-volumes.init.yml"

  - name: docker-stack.deploy|init networks
    vars:
      networks: "{{ _stack_deploy.vars.networks | default(networks_default,true) }}"
      networks_default: "{{ _stack_deploy.default.networks | default({},true) }}"
      networks_share: "{{ _stack_deploy.share.networks | default({},true) }}"
    when: networks | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-networks.init.yml"

  - name: docker-stack.deploy|add configs
    vars:
      configs: "{{ _stack_deploy.vars.configs | default(configs_default,true) }}"
      configs_default: "{{ _stack_deploy.default.configs | default({},true) }}"
      configs_share: "{{ _stack_deploy.share.configs | default({},true) }}"
    when: configs | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-configs.add.yml"

  - name: docker-stack.deploy|add secrets
    vars:
      secrets: "{{ _stack_deploy.vars.secrets | default(secrets_default,true) }}"
      secrets_default: "{{ _stack_deploy.default.secrets | default({},true) }}"
      secrets_share: "{{ _stack_deploy.share.secrets | default({},true) }}"
    when: secrets | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-secrets.add.yml"

  - name: docker-stack.deploy|add labels
    vars:
      labels: "{{ _stack_deploy.vars.labels | default(labels_default,true) }}"
      labels_default: "{{ _stack_deploy.default.labels | default({},true) }}"
      labels_share: "{{ _stack_deploy.share.labels | default({},true) }}"
    when: labels | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-labels.add.yml"

  - name: docker-stack.deploy|push envs
    vars:
      envs: "{{ _stack_deploy.vars.envs | default(envs_default,true) }}"
      envs_default: "{{ _stack_deploy.default.envs | default({},true) }}"
      envs_share:
        mode: value
        group: docker-manager
    when: envs | length > 0
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-envs.push.yml"

  - vars:
      composes: "{{ _stack_deploy.vars.composes | default(composes_default,true) }}"
      composes_default: "{{ _stack_deploy.default.composes | default({},true) }}"
      composes_share:
        mode: value
        group: docker-manager
    when: composes | length > 0
    block:
    - name: docker-stack.deploy|push composes
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-composes.push.yml"

    - name: docker-stack.deploy|add compose
      vars:
        compose_share:
          group: docker-manager
        compose:
          type: stack
          name: "{{ _stack_deploy.name | default(workpath.name,true) }}"
          path: "{{ _stack_deploy.path | default(workpath.remote.full,true) }}"
          files: "{{ composes | map(attribute='file') }}"
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-compose.add.yml"

- name: docker-stack.deploy|unfact param
  run_once: true
  ansible.builtin.set_fact:
    _stack_deploy: !!null
