# code: language=ansible
---

- name: qinglong-ninja.deploy|wait container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.wait.yml"
  vars:
    container:
      name: qinglong
      until:
        - container_info.exists
      retries: 60
      delay: 60

- name: qinglong-ninja.deploy|exec container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.exec.yml"
  vars:
    container:
      container: qinglong
      command:
        - "bash -c 'git -C /ql/ninja pull || git clone https://github.com/MoonBegonia/ninja.git /ql/ninja'"
        - "bash -c 'cd /ql/ninja/backend && pnpm install'"
        - "bash -c 'cd /ql/ninja/backend && pm2 start'"
        - "bash -c 'echo \"\ncd /ql/ninja/backend\npm2 start\" >> /ql/data/config/extra.sh'"
      register: container_exec

- name: qinglong-ninja.deploy|print exec
  vars:
    docker_hostvars: "{{ hostvars | dict2items
      | selectattr('key','in',groups['docker'])
      | selectattr('value.container_exec','defined') }}"
  ansible.builtin.pause:
    seconds: 1
    prompt: |
      {% for host in docker_hostvars %}

      [{{ host.key }}] =>
      --------------------------------------------------
      {% for item in host.value.container_exec.results %}
      {{ item.stdout | default('',true) }}
      {{ item.stderr | default('',true) }}
      {% endfor %}
      {% endfor %}
