# code: language=ansible
---

- name: netbird-network.up|wait container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.wait.yml"
  vars:
    container:
      name: netbird
      until:
        - container_info.exists
      retries: 60
      delay: 60

- name: netbird-network.up|exec container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.exec.yml"
  vars:
    container:
      container: netbird
      command: "netbird up --setup-key={{ netbird.setupkey }} {{ netbird.network.flags | default('',true) }}"
      register: container_exec
