# code: language=ansible
---

- rescue:
  - name: influxdb-snapshot.backup|rescue|fail tasks
    when:
      - snapshot | type_debug == 'dict'
    ansible.builtin.fail:
      msg: "backup fail. exclude task var assert."

  block:
  - name: influxdb-snapshot.backup|assert var
    ansible.builtin.assert:
      that:
        - snapshot | type_debug == 'dict'
      msg: "task var assert fail 'snapshot'"
      quiet: true

  - name: influxdb-snapshot.backup|fact param
    vars:
      comb_default:
        when: true
        var:
          # portable format only support oss 1.5–1.8
          format: portable

          # empty mean all databases
          database: ''

          # influxdb snapshot backup destination
          directory: ''

          mode: 'a+rx'

          # link for backup destination
          link:
            path: ''
            target: ''

      comb_param:
        when: true
        var: "{{ snapshot | default({},True) }}"

      comb_dirlink:
        when: "{{ last.directory == '' }}"
        var:
          directory: "/var/lib/influxdb/snapshot/{{ last.database }}.{{ ansible_date_time.iso8601_basic_short }}Z"
          link:
            path: "/var/lib/influxdb/snapshot/{{ last.database }}.latest"
            target: "/var/lib/influxdb/snapshot/{{ last.database }}.{{ ansible_date_time.iso8601_basic_short }}Z"

      conditional: "{{ lookup('ansible.builtin.vars', name).when }}"
      item: "{{ lookup('ansible.builtin.vars', name).var }}"
      last: "{{ _snapshot | default({},true) }}"
    loop:
      - comb_default
      - comb_param
      - comb_dirlink
    loop_control:
      loop_var: name
    when: conditional
    ansible.builtin.set_fact:
      _snapshot: "{{ last | combine(item, recursive=true) }}"

  - name: influxdb-snapshot.backup|append commands
    vars:
      append_mkdir_target:
        when: "{{ _snapshot.directory == _snapshot.link.path and _snapshot.link.target !='' }}"
        cmd:
          - mkdir -m {{ _snapshot.mode }} -p {{ _snapshot.link.target }}
          - rm -f {{ _snapshot.link.path }}
          - ln -s -r {{ _snapshot.link.target }} {{ _snapshot.link.path }}

      append_backup:
        when: "{{ _snapshot.directory != '' }}"
        cmd:
          - mkdir -m {{ _snapshot.mode }} -p {{ _snapshot.directory | dirname }}
          - >
            influxd
            backup
            {{ (_snapshot.format == 'portable') | ternary('-portable','') }}
            {{ (_snapshot.database != '') | ternary('-db','') }}
            {{ (_snapshot.database != '') | ternary(_snapshot.database,'') }}
            {{ _snapshot.directory }}

      append_link_target:
        when: "{{ _snapshot.directory == _snapshot.link.target and _snapshot.link.path !='' }}"
        cmd:
          - rm -f {{ _snapshot.link.path }}
          - ln -s -r {{ _snapshot.link.target }} {{ _snapshot.link.path }}
          - chmod -R {{ _snapshot.mode }} {{ _snapshot.link.target }}

      conditional: "{{ lookup('ansible.builtin.vars', name).when }}"
      item: "{{ lookup('ansible.builtin.vars', name).cmd }}"
      last: "{{ _snapshot.commands | default([],true) }}"

      result: "{{ last + item }}"
      combine:
        commands: "{{ result }}"
    loop:
      - append_mkdir_target
      - append_backup
      - append_link_target
    loop_control:
      loop_var: name
    when: conditional
    set_fact:
      _snapshot: "{{ _snapshot | combine(combine, recursive=true) }}"

  - name: influxdb-snapshot.backup|wait container
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.wait.yml"
    vars:
      container:
        name: influxdb
        until:
          - container_info.exists
        retries: 60
        delay: 60

  - name: influxdb-snapshot.backup|exec container
    include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.exec.yml"
    vars:
      container:
        container: influxdb
        command: "{{ _snapshot.commands | select() }}"
        register: container_exec

  - name: influxdb-snapshot.backup|print exec
    vars:
      docker_hostvars: "{{ hostvars | dict2items
        | selectattr('key','in',ansible_play_hosts)
        | selectattr('value.container_exec','defined') }}"
    ansible.builtin.pause:
      seconds: 1
      prompt: |
        {% for host in docker_hostvars %}

        [{{ host.key }}] =>
        --------------------------------------------------
        {{ host.value.container_exec.stdout | default('',true) }}
        {{ host.value.container_exec.stderr | default('',true) }}
        {% endfor %}
