#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: install
  hosts: linux
  environment: 
    PATH: "{{ ansible_env.PATH}}:/usr/local/anaconda/bin"
  tasks:

    - vars:
        mode: "{{ conda.mode | default('role',true) }}"
      when: conda is defined
      block:
      - name: andrewrothstein role conda
        vars:
          anaconda_mirror: "{{ conda.mirror | default('https://repo.continuum.io/archive',true) }}"
          anaconda_ver: "{{ conda.version | default('2024.06-1',true) }}"
          anaconda_pkg_update: false
          anaconda_make_sys_default: "{{ conda.profile | default(false,true) }}"
        when: mode == 'andrewrothstein'
        ansible.builtin.include_role:
          name: andrewrothstein.anaconda

      - name: robertdebock role conda
        vars:
          anaconda_version: "{{ conda.version | default('2024.10-1',true) }}"
        when: mode == 'robertdebock'
        ansible.builtin.include_role:
          name: robertdebock.anaconda

    # TODO 支持 https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html

    # TODO 支持 将目录添加到用户profile中

    - name: info conda
      ansible.builtin.shell:
        cmd: conda info
      register: info_sh
      ignore_errors: true

    - name: info print
      vars:
        linux_hostvars: "{{ hostvars | dict2items
          | selectattr('key','in',ansible_play_hosts)
          | selectattr('value.info_sh','defined') }}"
      ansible.builtin.pause:
        seconds: 1
        prompt: |
          {% for host in linux_hostvars %}

          [{{ host.key }}] =>
          --------------------------------------------------
          {{ host.value.info_sh.stdout | default('',true) }}
          {{ host.value.info_sh.stderr | default('',true) }}
          {% endfor %}
