#!/usr/bin/env -S ansible-playbook -K -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: up
  hosts: linux
  tasks:

  - when: tailscale.authkey is defined
    include_tasks: auth-key/ansible-tasks.up.yml

  - when: tailscale.authkey is undefined
    include_tasks: admin-console/ansible-tasks.up.yml
