version: "3.8"

volumes:
  dotfile:
    name: external_vol-cli_proxy_api-dotfile
    external: true

networks:
  cli-proxy-api:

services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api:latest
    env_file: external_env-all.env
    volumes:
      - dotfile:/root/.cli-proxy-api
      - ./bind_file-config.yaml:/CLIProxyAPI/config.yaml
    networks:
      - cli-proxy-api
    ports:
      - 8317
    # network_mode: bridge
    container_name: cli-proxy-api
    restart: always
