# code: language=ansible
---

- name: admin-console.up|get lan
  ansible.builtin.shell: "ip route | grep src | grep br-lan | awk '{print $1}'"
  register: lan_get

- name: admin-console.up|up async network
  vars:
    flags: "{{ tailscale.network.flags | default('',true) | replace('\n','') }}"
  ansible.builtin.shell: "sh -c 'tailscale up --advertise-routes={{ lan_get.stdout }} {{ flags }} > /tmp/tailscale.up.log 2>&1'"
  register: async_up
  async: 300
  poll: 0

- name: admin-console.up|status async finished
  ansible.builtin.async_status:
    jid: "{{ async_up.ansible_job_id }}"
  register: async_status
  until: async_status.finished
  # retry once in 5 seconds
  retries: 1
  delay: 5
  ignore_errors: true

- name: admin-console.up|grep log authenticate url
  when: not async_status.finished
  # not work see https://github.com/ansible/ansible/issues/79683
  # ansible.builtin.wait_for:
  #   path: /tmp/tailscale.up.log
  #   search_regex: "To authenticate, visit:"
  ansible.builtin.command:
    cmd: "grep 'To authenticate, visit:' /tmp/tailscale.up.log"
  retries: 60
  register: log_grep
  until: log_grep is successful

- name: admin-console.up|slurp log authenticate url
  ansible.builtin.slurp:
    src: /tmp/tailscale.up.log
  register: log_slurp

- name: admin-console.up|print log authenticate url
  vars:
    openwrt_hostvars: "{{ hostvars | dict2items
      | selectattr('key','in',ansible_play_hosts)
      | selectattr('value.log_slurp','defined') }}"
  ansible.builtin.pause:
    seconds: 1
    prompt: |
      {% for host in openwrt_hostvars %}

      [{{ host.key }}] =>
      --------------------------------------------------
      {% if host.value.log_slurp.content is defined %}
      {{ host.value.log_slurp.content | b64decode }}
      {% endif %}
      {% endfor %}

- name: admin-console.up|status async finished
  ansible.builtin.async_status:
    jid: "{{ async_up.ansible_job_id }}"
  register: async_status
  until: async_status.finished
  # retry every 60 seconds for 15 minutes
  retries: 15
  delay: 60

- name: admin-console.up|slurp log finished
  ansible.builtin.slurp:
    src: /tmp/tailscale.up.log
  register: log_slurp

- name: admin-console.up|print log finished
  vars:
    openwrt_hostvars: "{{ hostvars | dict2items
      | selectattr('key','in',ansible_play_hosts)
      | selectattr('value.log_slurp','defined') }}"
  ansible.builtin.pause:
    seconds: 1
    prompt: |
      {% for host in openwrt_hostvars %}

      [{{ host.key }}] =>
      --------------------------------------------------
      {% if host.value.log_slurp.content is defined %}
      {{ host.value.log_slurp.content | b64decode }}
      {% endif %}
      {% endfor %}
