version: "3.8"

volumes:
  config:
    name: external_vol-frigate-config
    external: true
  storage:
    name: external_vol-frigate-storage
    external: true

services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.0-beta6
    env_file: external_env-frigate.env
    volumes:
      - ./bind_file-frigate.yml:/config/config.yml
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - storage:/media/frigate
    ports:
      - 5000:5000
      - 8554:8554
      - 8555:8555/tcp
      - 8555:8555/udp
    container_name: frigate
    restart: unless-stopped
    shm_size: 64mb
    privileged: true
    cap_add:
      - CAP_PERFMON
