# code: language=ansible
---

- name: zerotier-network.join|wait container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.wait.yml"
  vars:
    container:
      name: zerotier
      until:
        - container_info.exists
      retries: 60
      delay: 60

- name: zerotier-network.join|fact commands
  loop: "{{ zerotier.networks | default([],true) }}"
  loop_control:
    loop_var: network_id
  ansible.builtin.set_fact:
    zerotier_join_cmds: "zerotier-cli join {{ network_id }}"

- name: zerotier-network.join|exec container
  include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.exec.yml"
  vars:
    container:
      container: zerotier
      command: "{{ zerotier_join_cmds }}"
      register: container_exec
