#!/usr/bin/env -S ansible-playbook -i ${PWD}/ansible-inventories
# code: language=ansible
---

- name: deploy
  hosts: docker
  tasks:

    - name: fact workspace
      include_tasks: "{{ workspace.local }}/.seed/ansible-tasks/seed-workspace.fact.yml"

    - name: fact workpath
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-workpath.fact.yml"

    - name: deploy container
      include_tasks: "{{ workspace.local }}/{{ workspace.seedpath }}/ansible-tasks/seed-docker/docker-container.deploy.yml"
      vars:
        container:
          vars: "{{ headscale | default({},true) }}"
          default:
            volumes:
              - name: external_vol-headscale-etc
                driver: local
              - name: external_vol-headscale-lib
                driver: local
            container:
              detach: true
              restart_policy: always
              command: headscale serve
              volumes:
                - external_vol-headscale-etc:/etc/headscale
                - external_vol-headscale-lib:/var/lib/headscale
                - "{{ workpath.remote.full }}/bind_file-config.yaml:/etc/headscale/config.yaml"
              ports:
                - "8280:8080"
              hostname: headscale
              name: headscale
              image: headscale/headscale:0.20.0-debug
