version: "3.8"

volumes:
  trash:
    name: external_vol-dupeguru-trash
    external: true
  config:
    name: external_vol-dupeguru-config
    external: true
  storage:
    name: external_vol-dupeguru-storage
    external: true

services:
  dupeguru:
    image: jlesage/dupeguru:latest
    env_file: external_env-all.env
    volumes:
      - trash:/trash:rw
      - config:/config:rw
      - storage:/storage:rw
    ports:
      - 5800:5800
    container_name: dupeguru
    privileged: true
    restart: always
    user: root:root
